### ISSUE TITLE
Document the use of DNS names to reach AWS reasources

### ISSUE THREAD

**Issue by mikkelhegn** [fermyon/developer#102]
AWS EC2 instances need to be referenced by their public IP, or by a DNS name that resolves to their public IP.

**Comment by tpmccallum** [comment]
See linear.app's Developer Docs team for more information.

**Comment by tpmccallum** [comment]
Some more information would be appreciated. Happy to follow up with testing/writing; just not sure what this refers to i.e. application URL.
Thanks

**Comment by mikkelhegn** [comment]
No idea :-) closing this...
