### ISSUE TITLE
Add FAQ to address that request count quotas are per month

### ISSUE THREAD

**Issue by macolso** [fermyon/developer#1045]
A user recently asked if the request limit for the free tier was per month or in total for Fermyon Cloud (the answer is per month), and whether that's spread across apps or per app (it's spread across apps). We should update our FAQ to include that https://developer.fermyon.com/cloud/faq

**Comment by tpmccallum** [comment]
So the quota is per month and is spread across all apps for a single Cloud account?
Is the above statement technically correct @macolso

**Comment by tpmccallum** [comment]
This is fixed by https://github.com/fermyon/developer/pull/1087

**Comment by tpmccallum** [comment]
Fixed by https://github.com/fermyon/developer/pull/1087
