### ISSUE TITLE
Is the Kubernetes k3d shim version correct?

### ISSUE THREAD

**Issue by itowlson** [fermyon/developer#1053]
In https://developer.fermyon.com/spin/v2/kubernetes#next-steps we direct people to `ghcr.io/deislabs/containerd-wasm-shims/examples/k3d:v0.8.0`.  https://github.com/deislabs/containerd-wasm-shims/blob/main/containerd-shim-spin/quickstart.md#start-and-configure-a-k3d-cluster shows a different version.

**Comment by vdice** [comment]
Thanks for spotting; the latest v0.10.0 shim version should be used in the docs.  PR submitted in https://github.com/fermyon/developer/pull/1061.
