### ISSUE TITLE
Spin Up Hub SEO issues - API crawler visibility and broken links

### ISSUE THREAD

**Issue by flynnduism** [fermyon/developer#1054]
[A user message](https://fermyon.slack.com/archives/C044P2DFTRS/p1701020261521979) was flagging how some search queries are leading to broken links.

<img width="880" alt="Screen Shot 2023-11-26 at 9 38 24 AM" src="https://github.com/fermyon/developer/assets/686194/2ca9bdaf-ec3a-4395-8031-bdde5f4d5f9f">

## Crawler Indexing

These [API urls](https://developer.fermyon.com/api/hub/template_spin_fileserver) appearing in search 
**probably shouldn't be indexed or crawled** in the same way as user-readable pages.

## Spin Up Hub SEO

Interestingly, the content for this Spin Up Hub entry (`template_spin_fileserver`) which contains the terms react, route, and fermyon does not perform as well as the the API endpoint that the user found here. Looks to me that the actual webpage does not show up in search results - @tpmccallum seeking your wisdom here to help assess what's happening here.

```
// crawler visibility:
✅ https://developer.fermyon.com/api/hub/template_spin_fileserver
❌ https://developer.fermyon.com/hub/preview/template_spin_fileserver
```

If I try searching for the Spin Up Hub text, verbatim, I'll see the GitHub page but not the hub page.

<img width="982" alt="Screen Shot 2023-11-26 at 9 48 29 AM" src="https://github.com/fermyon/developer/assets/686194/edca029d-4b13-49cb-a417-3093c3655a0c">

@karthik2804 👀 

- [x] @tpmccallum to re-submit the sitemap URL, to our Google Search Console, after fix is pushed and URL values in the sitemap's `loc` element are correct.

**Comment by tpmccallum** [comment]
I just left a comment on https://github.com/fermyon/developer/pull/1055 that suggests we utilize a redirect at the manifest level (so the sitemap renders the correct URLs by default).
The great news is I can submit a new sitemap to the Google Search Console as soon as we push a fix. 
Thanks, @flynnduism and @karthik2804, for diving into this one so quickly.

**Comment by tpmccallum** [comment]
Fixed and sitemap submitted.
Thanks again @flynnduism and @karthik2804
