### ISSUE TITLE
Tag filter in Developer Hub removes itself in Chrome 

### ISSUE THREAD

**Issue by taylols** [fermyon/developer#1107]
When trying to filter by tags in Developer Hub, the page refreshes and removes the filter entirely. 

https://github.com/fermyon/developer/assets/28018084/841f4537-a7d8-4958-adaa-fa9f45feec50

**Comment by itowlson** [comment]
@karthik2804 do you have bandwidth to investigate please?

**Comment by karthik2804** [comment]
I'll take a look at it tomorrow.
