### ISSUE TITLE
Deploying a Spin application on Kubernetes no longer requires a Dockerfile

### ISSUE THREAD

**Issue by radu-matei** [fermyon/developer#1109]
As of https://github.com/deislabs/containerd-wasm-shims/releases/tag/v0.10.0

ref https://developer.fermyon.com/spin/v2/kubernetes

**Comment by itowlson** [comment]
While we're editing that page, it it still true that AKS apps need to downgrade to the 1.0.0-rc.1 SDK?  Has AKS not updated their shim?

**Comment by itowlson** [comment]
The page currently mentions using `spin k8s scaffold` to create a Dockerfile and a `deploy.yaml` (https://developer.fermyon.com/spin/v2/kubernetes#spin-k8s-scaffold).

* Is `deploy.yaml` still needed?
* If so, do we need an uipdate to the k8s plugin to not create the Dockerfile, or should we retain it but have the docs explain it's not needed?

I assume the references to `spin k8s build` and `spin k8s push` both go away in favour of `spin registry push --build`?

**Comment by itowlson** [comment]
And this fragment from the generated deployment manifest looks wrong.  I assume this is meant to match https://github.com/deislabs/containerd-wasm-shims/blob/main/containerd-shim-spin/quickstart.md#deploy-the-application.

![image](https://github.com/fermyon/developer/assets/865538/13b34b08-2d32-48a7-8390-94a552f2db26)

**Comment by vdice** [comment]
> I assume the references to spin k8s build and spin k8s push both go away in favour of spin registry push --build?

I think those commands are still needed if the shim is < 0.10.0 (and maybe if Spin is pre-2.0?), as they build and push the wrapping Dockerfile, as opposed to the Spin app itself, directly (which is the preferred, shim 10.0+/Spin 2.0+ method).  

> ETA: The shim docs say to use kubectl apply - should we remove references to spin k8s deploy in favour of that?

It looks like both boil down to the same thing... but I imagine the shim docs are more up-to-date.  I'm also expecting an update to the `k8s` plugin in the near future, so usage will most likely change (another vote for going pure `kubectl apply` for now).

> (...and... this kubernetes.io/ingress.class annotation should be replaced by an ingressClassName in spec?)

Yes

**Comment by itowlson** [comment]
Hmm, I had not realised the k8s plugin was a bash script.  Would that even work on Windows?  The manifest says it does but I'm not sure how!

**Comment by vdice** [comment]
😬 Good point!  Is it too early to require shim 0.10.0+ in the docs then (at least for the v2 version), and just go shim/kubectl instructions until the plugin can be revamped?

**Comment by itowlson** [comment]
I'll mention the plugin way but also give the manual way.

**Comment by itowlson** [comment]
Okay I've addressed the immediate issue though someone Kubernetical needs to have a Paddington Bear stare at that page and figure out how much of it is still correct - I'm guessing things like the AKS SDK version are probably not...  @tpmccallum would it make sense for you to pick this up?
