### ISSUE TITLE
Add beacon for reo.dev

### ISSUE THREAD

**Issue by flynnduism** [fermyon/developer#1136]
We want to add the reo.dev tool to the Developer site, it grants insights around GH and project downloads...

```
<!-- Start of Reo Javascript --> <script type=“text/javascript”> !function(){var e,t,n;e=“57fed4b17f82a05",t=function(){Reo.init({clientID:“57fed4b17f82a05”})},(n=document.createElement(“script”)).src=“https://static.reo.dev/”+e+“/reo.js”,n.async=!0,n.onload=t,document.head.appendChild(n)}(); </script> <!-- End of Reo Javascript -->
```

Two steps required:

1. Adding the code in the site templates
2. Review whether this beacon sets a cookie in the browser - likely it does, and would require updates to [our consent configuration](https://github.com/fermyon/developer/blob/454d29db098ddef85b896809399b148a7e632fe3/static/js/src/main.js#L26)

**Comment by karthik2804** [comment]
closed by #1137
