### ISSUE TITLE
Add the ability to link to individual fields within the spin manifest documentation

### ISSUE THREAD

**Issue by endocrimes** [fermyon/developer#1155]
When trying to share spin documentation with people it would often be useful to link to a specific field in the manifest (e.g when mentioning `allowed_outbound_hosts`) - unfortunately you can only currently link to the overall _table_ for a section, a la https://developer.fermyon.com/spin/v2/manifest-reference#the-component-table.

**Comment by itowlson** [comment]
@karthik2804 Is there a way to automate this in Bartholomew (like it does for headings) or is it just down to sticking `<a>` elements in by hand?

**Comment by karthik2804** [comment]
Of the top of my head I can think of a few ways to achieve this. 

- like you pointed out, we can manually add link tags
- we can add a shortcode that automatically grabs the next element and create an anchor 
- if it is limited to just this page or just a couple other we can write some JavaScript to deal with it automatically on the frontend.

**Comment by VamshiReddy02** [comment]
Hey @karthik2804 , can I work on this issue?

**Comment by karthik2804** [comment]
@VamshiReddy02 sure but I am not sure we have a preferred approach here yet.

**Comment by itowlson** [comment]
I have no opinion on the approach I just want @endocrimes to be happy

@karthik2804 decision or leave it up to @VamshiReddy02?

**Comment by karthik2804** [comment]
I would be in favor of doing something with an annotating comment before the table and just writing some JS to generate the anchor links on the front end. 

@VamshiReddy02 let me know if you have other ideas or if you need help with the above approach.
