### ISSUE TITLE
Wasm Languages Guide: Add Forest page

### ISSUE THREAD

**Issue by technosophos** [fermyon/developer#1184]
Forest functional programming language: https://github.com/forest-lang/forest-compiler

**Comment by tpmccallum** [comment]
Hi @vdice 
Last commit in the Forest compiler was ~4 years ago.
The readme says, there is no standard library of data structures or ways to share packages and "So, very not ready for even simple applications."
I think we  can close this issue and revisit it if we see some activity in the Forest.
