### ISSUE TITLE
What is the precise meaning of the Other environment in the top 20 languages guide?

### ISSUE THREAD

**Issue by Mossaka** [fermyon/developer#1185]
First I want to thank you for putting out this programming language guide for Wasm and it helped me a lot to learn what PLs support WASI environment. When I first read the guide, I was confused about the "Other" column in the top 20 languages. I later figured it out it meant non-browser environments. But this is a bit vague. Do you mean host environments with an operating systems like Windows or Unix? I would recommend to make it more specific, probably by saying these languages could work in Linux OS. 

Another note is that the "Wasm languages" and "Other Notable Languages" have a section where the "Other" column is replaced with "CLI". Does "CLI" mean the same thing as "Other" in the previous section?

**Comment by tpmccallum** [comment]
Hi, thanks for noticing this. I see that the "other" column is no longer on the top 20 languages table.
Given the tables have been updated and some time has elapsed, @Mossaka, are you fine with us closing this issue?

Great news: we have updated the content, and the wasm-languages section is now [part of the developer documentation](https://developer.fermyon.com/wasm-languages/webassembly-language-support). You will see a lot more regular updates to the content from now on. Also, please feel free to add any new issues and use [the wasm-languages label](https://github.com/fermyon/developer/labels/wasm-languages). 

Also, you may have seen that we have a language support overview that discusses language (Rust, JS/TS, Python, TinyGo) support for Spin features (https://developer.fermyon.com/spin/v2/language-support-overview).

**Comment by tpmccallum** [comment]
Closing this, and can always reopen any issues with fresh ideas.
Thanks for the feedback; much appreciated.
