### ISSUE TITLE
add an example spin.toml to the application manifest reference 

### ISSUE THREAD

**Issue by michelleN** [fermyon/developer#1191]
It would be nice to either add or link to an example Spin.toml with the basics from the manifest reference.

**Comment by tpmccallum** [comment]
Hi @michelleN 
That's a great idea. I have added an example inline; because we can never guarantee that a link to a heading in another page somewhere will always be available. The example manifest I used is from the Rust HTTP template.

**Comment by tpmccallum** [comment]
Ref: https://github.com/fermyon/developer/pull/1196
