### ISSUE TITLE
Should use code block for the actual command

### ISSUE THREAD

**Issue by mikkelhegn** [fermyon/developer#121]

**Comment by rajatjindal** [comment]
in https://developer.fermyon.com/spin/quickstart

<img width="862" alt="Screen Shot 2022-11-02 at 10 09 31 AM" src="https://user-images.githubusercontent.com/612092/199399706-90a89f33-d838-4707-a88c-89f783cf440e.png">

the command `rustup target add wasm32-wasi` should be inside code block

**Comment by radu-matei** [comment]
This particular example has been fixed in #207 — any other examples where this needs to be addressed?

**Comment by tpmccallum** [comment]
See linear.app's Developer Docs team for more information.
