### ISSUE TITLE
Enhance how we add the anchor-link to individual table rows

### ISSUE THREAD

**Issue by tpmccallum** [fermyon/developer#1235]
Create a way to link to a specific individual row in a table that exists in the documentation, i.e. a user can share a link to the `source` row in the component table on the manifest reference page.

![Screenshot 2024-04-03 at 21 55 01](https://github.com/fermyon/developer/assets/9831342/bab68bf1-2f15-49b7-9184-aa788a42efe9)

The link to the specific individual row should consist of:
- the protocol & base domain (i.e. `https://developer.fermyon.com`)
- the path to the file (i.e. `/spin/v2/manifest-reference`)
- the closest parent heading (i.e. `#the-component-table`)
- the specific row's `name` value ( i.e. `-source`)

For example, `https://developer.fermyon.com/spin/v2/manifest-reference#the-component-table-source` (where the closest parent heading and specific row's name are separated by kebab-case)

**Comment by tpmccallum** [comment]
@karthik2804 had a suggestion of what would work to find the closest parent heading:

```javascript
function findNearestHeader(element) {
    var currentElement = element.parentNode;

    // Traverse up the DOM tree until a header element is found or no parent exists
    while (currentElement) {
      if (currentElement.nodeName.startsWith('h')) {
        // If the current element is a header element, return it
        return currentElement;
      }
      currentElement = currentElement.parentNode;
    }

    // If no header element is found in the ancestor elements, return null
    return null;
  }
```

I am looking forward to seeing if you have a breakthrough on this @VamshiReddy02. Thanks again for your contributions. They are greatly appreciated!

**Comment by VamshiReddy02** [comment]
Hey @tpmccallum, yesterday I did some research and made some changes in the code. Finally, I got this result. Could you please see and confirm if it's correct?
<img width="1440" alt="Screenshot 2024-04-04 at 8 26 24 AM" src="https://github.com/fermyon/developer/assets/99033623/5e151cf3-75e5-414b-8ec1-84728356d0e1">

**Comment by itowlson** [comment]
Just to throw some extra confusion on this, @tpmccallum had (long ago!) the suggestion of looking for the `heading-anchor` CSS class rather than a node name starting with `h`: https://github.com/fermyon/developer/pull/1165#issuecomment-1951654743.  This seems maybe safer, but I'll defer to @karthik2804 and Tim because my HTML knowledge stopped at "tables good."

@VamshiReddy02 That link looks perfect - this should be high-stability and low-ambiguity.  Thank you!

**Comment by karthik2804** [comment]
That looks good, one potential future addition that I might suggest is potentially a check to see if the id, exists if not try fallback to the closest header. This does not need to be a part of this PR. Could just be a good future addition.
