### ISSUE TITLE
Dependencies for `check-broken-links.sh`

### ISSUE THREAD

**Issue by ThorstenHans** [fermyon/developer#1237]
This repository contains a `.build/check-broken-links.sh` script which is executed as part of `npm run test`. 

The script checks if the following dependencies are installed on the local machine:

- `spin`
- `timeout`
- `blc`

Is there further information how one could install `timeout` and `blc`?

**Comment by vdice** [comment]
`blc` is added from its node_modules path in the script here: https://github.com/fermyon/developer/blob/main/.build/check-broken-links.sh#L40-L41

`timeout` is included in the [gnu coreutils pkg](https://www.gnu.org/software/coreutils/) which I think is usually present in most Linux distros and for my MacOS machine I've added via `brew install coreutils`.  Windows I am not sure 😅.  This could also be an opportunity to devise a different approach that would cut out this dependency in the script...

**Comment by tpmccallum** [comment]
Apologies if I am missing something - I normally run the following procedure when performing local preview/testing:

```bash
# Go into spin-up-hub section
cd spin-up-hub/
# NPM install
npm install
# Go back into just developer folder
cd ../
# NPM install
npm install
# Build the site for local preview
spin build
# Bartholomew's linting
bart check content/the-file-to-check.md
# Run the node linting and tests
npm run test
# Local preview the site at localhost:3000
spin up -e "PREVIEW_MODE=1"
```

**Comment by ThorstenHans** [comment]
Installing `coreutils` on my mac did the trick. I'll add a note about that to the testing section of the contributing page in a dedicated PR
