### ISSUE TITLE
The configuration options documentation

### ISSUE THREAD

**Issue by mikkelhegn** [fermyon/developer#124]

**Comment by rajatjindal** [comment]
under https://developer.fermyon.com/spin/configuration, the `spin.toml` config options are documented as list. we should probably consider changing the documentation to 

tabular format e.g. https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.22/#container-v1-core

OR

we can change styling a bit. e.g. https://stripe.com/docs/api/events/object

**Comment by radu-matei** [comment]
ref #215

**Comment by tpmccallum** [comment]
See linear.app's Developer Docs team for more information.
