### ISSUE TITLE
CLI Reference defaults to oldest version of Spin

### ISSUE THREAD

**Issue by flynnduism** [fermyon/developer#1289]
![Screen Shot 2024-05-17 at 10 40 53 AM](https://github.com/fermyon/developer/assets/686194/9df83b3d-1315-493c-a5fb-3879965ea760)

Ideally the order of the version tabs should be reversed.

Seems like a markdown render issue that may need some hacking to reverse the sort order.

**Comment by tpmccallum** [comment]
Hi @karthik2804 
Just curious what you had in mind for a fix (so that we can have the default tab open to the latest version)?
I can make the edit, just don't want to duplicate work if you already had an idea in the works.

**Comment by karthik2804** [comment]
I have not started but it is pretty straightforward. we just need to add a classname to the `<ul>` element and then have that class have the following style 
```
display: flex;
flex-direction: row-reverse;
```
