### ISSUE TITLE
Internal routing wildcard does not seem to work

### ISSUE THREAD

**Issue by technosophos** [fermyon/developer#1364]
Version: Spin 2.6.0
SDK: JS SDK 2.0

The [documentation](https://developer.fermyon.com/spin/v2/http-outbound#local-service-chaining) indicates that the correct pattern for matching any internal route is:

```
allowed_outbound_hosts = ["*://*.spin.internal"]
```

However, if I use that pattern, I get the following error:

```
Error: Failed to load manifest from "spin.toml"

Caused by:
   0: Failed to load Spin app from "spin.toml"
   1: Failed to load component `frontend`
   2: `allowed_outbound_hosts` is malformed
   3: no port was provided and the scheme "*" does not have a known default port number
```

Switching it to a list of exact known components fixes the problem.

I suspect this is just a typo somewhere in the docs. I just don't know how to fix.

**Comment by itowlson** [comment]
Yeah I think it should be `http://*.spin.internal`, like the ones immediately above.  Not sure why we have the `*` scheme there.
