### ISSUE TITLE
Component dependencies feature

### ISSUE THREAD

**Issue by itowlson** [fermyon/developer#1372]
In Spin 3, we can satisfy components' imported interfaces by wiring them up in the manifest.  The v3 docs will need to cover this.  We should consider:

* Reference documentation
* Concepts documentation (probably fits into the "writing apps" and/or "building apps" section, or might need a new unit about components as a concept, component registries, etc.)
* Any caveats around Cloud / SpinKube / registries / etc.
* Tutorial / example
  * We could have some pre-built demo components and WITs for this in the Fermyon registry (although I am not sure what tooling can use OCI registries right now)

**Comment by fibonacci1729** [comment]
I agree re: adding components as a concept and component registries would be really useful given that `source` and `dependencies` both reference "registry" as a concept; however, I'm partial to including that as a followup action item.

**Comment by vdice** [comment]
Closed by https://github.com/fermyon/developer/pull/1393
