### ISSUE TITLE
Something gnarly happening with this code block

### ISSUE THREAD

**Issue by lann** [fermyon/developer#1375]
Same effect in both Firefox and Chrome on Linux.

https://developer.fermyon.com/wasm-languages/grain

![2024-08-30T20:18:14,547564486+02:00](https://github.com/user-attachments/assets/01abb5f4-d91f-4afb-813f-285c3cea19e4)

**Comment by itowlson** [comment]
And differently borked in Edge on Windows 11.  I think we've seen this before - @karthik2804 @flynnduism ring any bells?

![image](https://github.com/user-attachments/assets/5b28d0e0-1f74-4da7-a767-f6a64b131859)

**Comment by karthik2804** [comment]
I believe there is some messed up formatting. I can take a look in the morning.

**Comment by itowlson** [comment]
Oh, the block has a `grain` highlight marking.  I bet the highlighter doesn't recognise that and chooses to express its confusion in the tradition of its people.

**Comment by karthik2804** [comment]
@itowlson you are right. I will open a PR.
