### ISSUE TITLE
Selective deployments/application splitting doc

### ISSUE THREAD

**Issue by vdice** [fermyon/developer#1414]
Add a doc around the selective deployment functionality in Spin 3

**Comment by itowlson** [comment]
Can you be more specific please @vdice?  We have some content at https://developer.fermyon.com/spin/v3/running-apps#splitting-an-application-across-environments; is there something more needed?

**Comment by vdice** [comment]
🤦 That's exactly the doc I was looking for!  Apologies, I missed this amidst the big v3 docs push!  Thanks @itowlson.
