### ISSUE TITLE
Unclear documentation around mixing trigger types

### ISSUE THREAD

**Issue by dehuszar** [fermyon/developer#1418]
Greetings!

I am working through creating a Spin application and was intending to mix the http and cron triggers to invoke different components.  The [Writing Applications](https://developer.fermyon.com/spin/v3/writing-apps) page indicates that trigger types cannot be mixed in an application.  But if I then go over to the [Triggers](https://developer.fermyon.com/spin/v3/triggers#:~:text=In%20Spin%202.3%20and%20later,%20an%20application%20can%20contain%20triggers%20of%20different%20types) page it says `In Spin 2.3 and later, an application can contain triggers of different types`.

I presume the latter is true, but I almost began a major refactor on my application as I had reviewed the Writing Apps page first.

**Comment by dehuszar** [comment]
Thanks!  At the risk of getting off topic, is there a future where cron triggers would be supported on Fermyon Cloud?  Additionally, I've seen SpinKube being pushed, but I'm firmly in the HashiStack (Nomad/Consul/Vault) space.  Are those resources and repos going to continue to be supported?

**Comment by itowlson** [comment]
It's something we get asked for quite a bit but there are challenges with running a cron trigger in a distributed environment.  @radu-matei do we have any guidance/cookbooks for HashiStack?

**Comment by dehuszar** [comment]
[This](https://github.com/fermyon/spin/blob/967fdf368612478cef176bccc491faffad680050/deploy/spin-docs.nomad#L50) has been around for a while, and I've even constributed PRs.  I'm mostly just trying to get a sense, directionally, whether Nomad resources will continue to be kept up-to-date with the introduction of SpinKube.  It sounds like y'all are going to be continuing to use the HashiStack for production (please correct me if I'm wrong), but for community use, it feels like there's been a divestment of energy.

Happy to take this to Discord if that's a better space for it.
