### ISSUE TITLE
AWS key-value backend

### ISSUE THREAD

**Issue by itowlson** [fermyon/developer#1422]
The runtime config page needs info about configuring AWS Dynamo key-value stores.

@ogghead do you have an example AWS runtime config you used for testing that you can share (redacted of course)?  If so I can work up some words around it and run them past you for review.  Otherwise I will figure it out from the code in your PR.

**Comment by ogghead** [comment]
[This is the config I used for testing](https://github.com/ogghead/TestDynamo/blob/main/rt-config.toml) -- this pulls Identity Access Management (IAM) role credentials from environment. It is also possible to pass access_key, secret_key, and optionally a token (AWS auth is... a bit odd) as [here](https://github.com/fermyon/spin/blob/main/crates/key-value-aws/src/lib.rs#L26) with usage [here](https://github.com/fermyon/spin/blob/main/crates/key-value-aws/src/lib.rs#L60)

It should be noted that the current implementation requires that the Dynamo table's primary key is "PK" and that the table has no secondary key, though we could quickly allow setting a custom primary key with another env variable if desired.

And apologies, I should have considered adding this documentation earlier! Thank you for tracking this @itowlson!

**Comment by itowlson** [comment]
Perfect - thanks!

**Comment by itowlson** [comment]
Thanks for the terminology check - I amended the PR
