### ISSUE TITLE
Ability to show instructions / code for multiple platforms using a toggle

### ISSUE THREAD

**Issue by radu-matei** [fermyon/developer#179]
It would be really cool if the code renderer for our docs website allowed a toggle we can use to show instructions / code samples for multiple platforms / languages (like Linux and Windows instructions, or how to write a component in multiple programming languages).

This would be similar to:

<img width="786" alt="image" src="https://user-images.githubusercontent.com/13103165/159831322-08c5f9b6-3d5d-4f7e-8e29-f718973bd546.png">

(source: [Cloud Run docs](https://cloud.google.com/run/docs/tutorials/image-processing#run_imageproc_handler_setup-nodejs))

**Comment by karthik2804** [comment]
I have a hacky implementation of this working with the front-end javascript and shortcodes that allows for toggling multiple different languages in code blocks but I am wondering where it could be used in the current state of the documentation for me to make an actual example.

**Comment by tpmccallum** [comment]
See linear.app's Developer Docs team for more information.
