### ISSUE TITLE
Cloud quickstart video does not show all the quickstart steps

### ISSUE THREAD

**Issue by mikkelhegn** [fermyon/developer#181]
The video on the cloud quickstart page does not show the four steps of the quickstart:
1. Install
2. Clone
3. Deploy
4. Open app

**Comment by tpmccallum** [comment]
See linear.app's Developer Docs team for more information.

**Comment by tpmccallum** [comment]
Hi @mikkelhegn 
Does this video still need updating; the docs show all of the steps (but the video only shows deploy). I think it is ok, because it makes the video short enough to loop once before the user scrolls down to see how to install etc. 
Thoughts?

**Comment by mikkelhegn** [comment]
I think the new quickstart video is good and covers what's needed here.
