### ISSUE TITLE
Contributions guide

### ISSUE THREAD

**Issue by mikkelhegn** [fermyon/developer#194]
Create a contributions guide for people wanting to contribute with documentations.

**Comment by tpmccallum** [comment]
Explain the [types of documentation](https://www.notion.so/fermyon/A-World-Class-Interactive-Developer-Showcase-For-Spin-and-Fermyon-Cloud-To-Create-Raving-Fans-30628d1cd67047789c6c39bafa7e8c49#25e8f86ccb98494293ad34ed1ebb19f0) and also discuss conventions around formatting headings, text and code.

**Comment by tpmccallum** [comment]
This new information can be added to [the already-existing docs contribution guide](https://developer.fermyon.com/cloud/contributing)

**Comment by tpmccallum** [comment]
See linear.app's Developer Docs team for more information.
