### ISSUE TITLE
Missing dependency and concept architecture suggestion

### ISSUE THREAD

**Issue by macolso** [fermyon/developer#200]
Two questions on the [Developing Spin Applications](https://developer.fermyon.com/spin/developing) article:
1. Why do we introduce spin up before spin build? From my perspective, it may be easier to build the user's understanding by starting with the lowest common denominator component and working up from there (pun semi-intended)
2. Are we missing the prerequisite step for installing cargo in this article? I believe the spin build command will fail if the user doesn't have [cargo](https://doc.rust-lang.org/cargo/getting-started/installation.html) installed. My understanding is cargo is not baked into the standard spin installation process.

**Comment by itowlson** [comment]
Re part 2: there's no `cargo` prerequisite per se.  `spin build` uses the build tool(s) appropriate to the app's (or component's) source code.  The example in that article shows `cargo` for a component built using Rust, but for a Go component it would be `tinygo`, for a C# component `dotnet`, etc.  We could link to the language guides to point people at the Wasm-specific build tools for their languages though.

**Comment by tpmccallum** [comment]
See linear.app's Developer Docs team for more information.
