### ISSUE TITLE
Broken link from index to install page

### ISSUE THREAD

**Issue by raymundovr** [fermyon/developer#209]
Hi,

While reading the docs I've noticed that the link within the contents of https://developer.fermyon.com/spin/index/ into the install page is broken.

Currently it is pointing to "https://developer.fermyon.com/spin/index/install" and it seems that should be "https://developer.fermyon.com/spin/install" as in the sidebar.

**Comment by rajatjindal** [comment]
curious question, did you open `https://developer.fermyon.com/spin/index/` directly or some other link pointed you to this page.

**Comment by raymundovr** [comment]
I went first here https://developer.fermyon.com/ and then clicked on the Spin link in the topbar

**Comment by rajatjindal** [comment]
hmm, that is strange. which browser are you using. (i tried on Edge on a Macbook, and can't reproduce it). It was a known issue and was fixed about 3-4 weeks back.

**Comment by raymundovr** [comment]
After your comment I just tried on Firefox private tab and it's not there, in fact the website looks totally different now!

So it seems that some cache needs to be invalidated.

You can close the ticket as it no longer describes the real problem.
