### ISSUE TITLE
Spin Config doesn't really explain `allowed_http_hosts`.

### ISSUE THREAD

**Issue by technosophos** [fermyon/developer#212]
https://developer.fermyon.com/spin/configuration

The `allowed_http_hosts` key isn't really explained there. There's no mention of insecure, and no discussion of whether wildcard domains are supported. Nor does it give an example of the format (e.g. do I add the scheme or not? Do I need port for non-80 ports?).

**Comment by radu-matei** [comment]
ref https://github.com/fermyon/spin/issues/930

**Comment by itowlson** [comment]
For reference when we come to write this: the behaviour is described in https://github.com/fermyon/spin/pull/727

**Comment by tpmccallum** [comment]
See linear.app's Developer Docs team for more information.
