### ISSUE TITLE
Update Spin GitHub

### ISSUE THREAD

**Issue by mikkelhegn** [fermyon/developer#22]
Once we release this portal, we need to freeze/remove the Spin repo docs.

- [x] Remove docs
- [x] #4 
- [ ] Spin readme.md needs an update with logo and text similar to quickstart

**Comment by radu-matei** [comment]
The Spin readme removed the old HackMD link.

Do we want to close this issue and track the Spin readme revamp in the repo?

**Comment by mikkelhegn** [comment]
> Do we want to close this issue and track the Spin readme revamp in the repo?

The Spin repo? I think that makes sense.
