### ISSUE TITLE
Layout not using full width of screen

### ISSUE THREAD

**Issue by mikkelhegn** [fermyon/developer#227]
The boxes in the middle are oddly sized given the width of the screen.

<img width="1892" alt="image" src="https://user-images.githubusercontent.com/12242001/206994325-ac5e8ac1-4821-424d-8e5a-aae81c2b3f1d.png">

**Comment by tpmccallum** [comment]
This looks like it has been resolved.
Boxes are a lot wider. and evenly spaced, under all resolutions; happy with this.
<img width="1746" alt="Screenshot 2023-02-08 at 5 33 03 pm" src="https://user-images.githubusercontent.com/9831342/217463781-5aafc92a-7b31-401c-b9fa-83af3ed7e742.png">
