### ISSUE TITLE
Language Guide overview

### ISSUE THREAD

**Issue by mikkelhegn** [fermyon/developer#228]
For the Language Guide section it would be great to have an overview page of what languages have SDK support, and what SDK features are available in each of those languages. This could also be used to direct users to the repositories with samples and templates for the SDKs.

**Comment by macolso** [comment]
+1 and call out any discrepancies between spin local and spin cloud

**Comment by tpmccallum** [comment]
Would a page like the following example be acceptable?


![Image](https://user-images.githubusercontent.com/9831342/222342976-3e49f7e2-af5c-4f1b-aa19-cd40193f0575.png)

For example, where each word like "Docs" would be a hyperlink to the actual docs. We could also link to code examples i.e. fermyon/examples area etc.

For now this could be manually updated by writing markdown, which is probably fine seeings how the table is not going to be that big/complex at the minute.

**Comment by tpmccallum** [comment]
If so we could take advantage of the fact that Bartholomew will accept HTML and just maintain using code such as the following:

```html
title = "Language Guide Overview"
template = "common_main"
date = "2022-01-01T00:00:01Z"
[extra]

---

<h1 id="spin-sdk---language-guide-overview">Spin SDK - Language Guide
Overview</h1>
<table>
<colgroup>
<col style="width: 20%" />
<col style="width: 20%" />
<col style="width: 20%" />
<col style="width: 20%" />
<col style="width: 20%" />
</colgroup>
<thead>
<tr class="header">
<th>Language</th>
<th>HTTP Trigger</th>
<th>Redis Trigger</th>
<th>Outbound HTTP</th>
<th>Outbound Redis</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Go</td>
<td>Local <br /> Cloud <br /> Docs <br /> Blog</td>
<td>Local <br /> Cloud <br /> Docs <br /> Blog</td>
<td>Local <br /> Cloud <br /> Docs <br /> Blog</td>
<td>Local <br /> Cloud <br /> Docs <br /> Blog</td>
</tr>
<tr class="even">
<td>Javascript</td>
<td>Local <br /> Cloud <br /> Docs <br /> Blog</td>
<td>Local <br /> Cloud <br /> Docs <br /> Blog</td>
<td>Local <br /> Cloud <br /> Docs <br /> Blog</td>
<td>Local <br /> Cloud <br /> Docs <br /> Blog</td>
</tr>
<tr class="odd">
<td>Python</td>
<td>Local <br /> Cloud <br /> Docs <br /> Blog</td>
<td>Local <br /> Cloud <br /> Docs <br /> Blog</td>
<td>Local <br /> Cloud <br /> Docs <br /> Blog</td>
<td>Local <br /> Cloud <br /> Docs <br /> Blog</td>
</tr>
<tr class="even">
<td>Rust</td>
<td>Local <br /> Cloud <br /> Docs <br /> Blog</td>
<td>Local <br /> Cloud <br /> Docs <br /> Blog</td>
<td>Local <br /> Cloud <br /> Docs <br /> Blog</td>
<td>Local <br /> Cloud <br /> Docs <br /> Blog</td>
</tr>
</tbody>
</table>
```

**Comment by tpmccallum** [comment]
@vdice has collaborated and generated the following Language Guide Overview; thank you so much Vaughn!!!
https://fermyontech-my.sharepoint.com/:x:/g/personal/vaughn_dice_fermyon_com/EY4KT-8I05xKoYpByWlWyhsBok_qHJr6Iyu8ffjmM8_Tyw

This can now be converted to the format which we talked about last week i.e. a multi-language code block style layout that lists each of the features in each of the language tabs.

**Comment by tpmccallum** [comment]
Once formatted this can go on the developer docs site as a separate menu item under the Spin - Language Guides section (with its own page that is linked to from the aforementioned menu)

**Comment by tpmccallum** [comment]
Made the decision in Spin 1.0 meeting to use multi-tab code blocks and add each of the features inside each separate tab in the holistic code block.

Also made the decision to add a separate but prominent feedback-link/feedback-mention for users to provide feedback (in case they are having issues or want to get a point across).

**Comment by tpmccallum** [comment]
First draft of markdown file is at PR https://github.com/fermyon/developer/pull/457

**Comment by tpmccallum** [comment]
Added and merged at https://github.com/fermyon/developer/pull/457
