### ISSUE TITLE
Where to document docs?

### ISSUE THREAD

**Issue by flynnduism** [fermyon/developer#240]
Looking at #239 , I wonder where instructions for this type of _more advanced_ formatting should surface?

Looking at the Spin and Cloud contribution guides, we could add notes pertaining to contributing Docs - but it would be great to do so global manner (root docs pages?) rather than on a per sub-project basis.

**Comment by tpmccallum** [comment]
I guess the more advanced docs like this should be in a subsection of "how to contribute".
It would be great to mention all of the linting and conventions also; so that contributors know that there is a standard of sorts (quality and consistency is implied).

**Comment by flynnduism** [comment]
@tpmccallum good idea, I agree a Contribution page would be a good home to denote how to achieve advanced formatting like this

**Comment by tpmccallum** [comment]
The developer docs now have a `common` area for the content relevant to two or more projects. Perhaps the best example of content relevant across many projects is the how to contribute to developer GH docs. Please see < https://developer.fermyon.com/common/contributing-docs >

In addition, we now have updated information on how to properly edit css, create the new search index, implement multi-tab code blocks and more, in the following PR. https://github.com/fermyon/developer/pull/368
