### ISSUE TITLE
Weird formatting on iPad OS

### ISSUE THREAD

**Issue by radu-matei** [fermyon/developer#242]
![173978A8-7949-464C-812C-AF478F396C99](https://user-images.githubusercontent.com/13103165/210078630-3d5baf49-5d40-48bc-96c8-6811bbbe06f8.jpeg)

**Comment by VestigeJ** [comment]
This is true for a regular monitor in portrait mode as well - if however I drop the site zoom through the browser to 90% all looks pretty well. 
![Screenshot 2023-01-05 at 4 45 38 PM](https://user-images.githubusercontent.com/8961630/210907174-35641a12-711c-4db5-99f7-29dd4c52cefa.png)


![Screenshot 2023-01-05 at 4 46 18 PM](https://user-images.githubusercontent.com/8961630/210907192-9c6040d0-d41c-44cf-a2ad-7e82c289f42f.png)

**Comment by radu-matei** [comment]
Thanks for the confirmation, @VestigeJ!

cc @flynnduism

**Comment by VestigeJ** [comment]
As a comparison - https://bartholomew.fermyon.dev/quickstart
barts quickstart at 100% is rendering fine by default
