### ISSUE TITLE
https://developer.fermyon.com/downloads/install.sh is outdated

### ISSUE THREAD

**Issue by smndtrl** [fermyon/developer#244]
The install.sh deployed is outdated (doesn't allow for linux aarch64) while the one in this repository has been updated on 16th dec.

**Comment by mikkelhegn** [comment]
This got merged earlier today: https://github.com/fermyon/developer/pull/237

**Comment by smndtrl** [comment]
Great. I just saw it in main with a date a few weeks ago and assumed it would be live as soon as it's main. That I happen to stumble upon it between commit and deploy is a happy accident in that case.
