### ISSUE TITLE
Lack of documentation for how to manage templates for Spin

### ISSUE THREAD

**Issue by mikkelhegn** [fermyon/developer#245]
I wanted to update a template, and couldn't find information regarding how to manage my local templates for Spin.

**Comment by tpmccallum** [comment]
Hi @mikkelhegn 
I can go ahead and create a new docs page Spin doc area that will show how to manage local templates for Spin.
This new doc will essentially be a **tutorial** that shows the current nuances i.e. how to install templates (https://developer.fermyon.com/cloud/cli-reference.md#install-templates), how to list templates ( https://developer.fermyon.com/cloud/cli-reference.md#list-templates ) and how to uninstall templates ( https://developer.fermyon.com/cloud/cli-reference.md#uninstall-templates ).

**Comment by itowlson** [comment]
A caveat on the `upgrade` command - this depends on some install tracking that we do not do in Spin 0.8.  So if users have an existing template installation from Spin 0.8 or before, `upgrade` will not work.  They'll need to do the old-skool `spin templates install --git ... --update` for each repo they have templates from.  After that, `spin templates upgrade` will work fine.

Actually I should improve the "missing info" handling to say this.

**Comment by tpmccallum** [comment]
Also, if you are finding this via web search, please note there is a video explaining how to manage templates and plugins at https://www.youtube.com/watch?v=eU7ng__1n08
