### ISSUE TITLE
Spin: Update documentation to indicate to update the templates upon spin upgrade

### ISSUE THREAD

**Issue by MChorfa** [fermyon/developer#251]
Please see:
https://github.com/fermyon/spin/issues/615#issuecomment-1376073184
https://github.com/fermyon/spin/issues/615#issuecomment-1376125638
related to: https://github.com/fermyon/spin/issues/990

**Comment by vdice** [comment]
(Moved to fermyon/developer where Spin docs are currently tracked.)
