### ISSUE TITLE
Code snippet is cut due to limited width

### ISSUE THREAD

**Issue by mikkelhegn** [fermyon/developer#253]
On this page, the code snippet cannot be read: https://developer.fermyon.com/spin/install#installing-a-specific-version-of-spin

<img width="989" alt="image" src="https://user-images.githubusercontent.com/12242001/214126287-5f014184-b7fb-4890-8f20-83fa43959343.png">

**Comment by tpmccallum** [comment]
This is now being fixed by https://github.com/fermyon/developer/pull/347

**Comment by tpmccallum** [comment]
This is now fixed; scroll and cursor can see/find content.
