### ISSUE TITLE
The `source` attribute for a component does not document the `url` and `digest` params.

### ISSUE THREAD

**Issue by technosophos** [fermyon/developer#258]
Inside of the configuration reference, `url` and `digest` are not documented. I learned about them by using `spin add` and then reverse-engineering.

https://developer.fermyon.com/spin/configuration

**Comment by vdice** [comment]
I believe we can close this.  `url` and `digest` are documented under `source` in https://developer.fermyon.com/spin/configuration#component-configuration and `spin add` is here: https://developer.fermyon.com/spin/template-authoring.md#supporting-spin-add
