### ISSUE TITLE
SDK reference / documentation

### ISSUE THREAD

**Issue by ThorstenHans** [fermyon/developer#259]
IMO it would be really helpful to have a reference and/or documentation for the Spin SDK. Although the SDK itself is not that big (yet) , users should be able to easily discover what's possible with the SDK and see which batteries are included. 

Although places like [docs.rs](https://docs.rs/) will typically serve SDK references and docs, https://developer.fermyon.com/spin should become that single hub where developers should find - at least links - for everything.

**Comment by melissaklein24** [comment]
The [Spin main page](https://developer.fermyon.com/spin/index) includes links to all the current SDKs documentation, the CLI reference, and tutorials on how to get started.
