### ISSUE TITLE
Add Spin CLI tool to path in "Let's Get Started" documentation

### ISSUE THREAD

**Issue by bcb44** [fermyon/developer#260]
Please share the following

Documentation topic (what would you like covered)?
Add spin tool to path in the documentation. Sort of weird to see it referenced by the file path to the executable instead of like normal cli apps. More appearance than anything functional. 

What documentation did you review and why was it not sufficient?
Here's [the link](https://developer.fermyon.com/cloud/quickstart). Looks like this is covered in other documentation of the same material so should just be a change for this page.

**Comment by tpmccallum** [comment]
Being fixed by PR https://github.com/fermyon/developer/pull/301
