### ISSUE TITLE
Document `--direct-mounts`

### ISSUE THREAD

**Issue by mikkelhegn** [fermyon/developer#262]
The `--direct-mounts` flag as talked about [here](https://github.com/fermyon/spin/issues/324#issuecomment-1409212106) is not documented in the [CLI-reference](https://developer.fermyon.com/cloud/cli-reference#up)

**Comment by itowlson** [comment]
There are in fact a bunch of `spin up` options that are not in that list e.g.

* `--allow-transient-writes`
* `--cache`
* `--disable-cache`
* `--follow` / `--follow-all`
* `--log-dir`
* `--runtime-config-file`

**Comment by tpmccallum** [comment]
Hi @mikkelhegn and @itowlson, just a quick note to let you know that there is a PR in to resolve the above.
Please see https://github.com/fermyon/developer/pull/263

**Comment by tpmccallum** [comment]
The following have been catered for.
```
--direct-mounts
--allow-transient-writes
--cache
--disable-cache
--follow / --follow-all
--log-dir
--runtime-config-file
```
In addition, there are smaller changes like `plugin` -> `plugins` etc.
