### ISSUE TITLE
Spin: install script version text

### ISSUE THREAD

**Issue by vdice** [fermyon/developer#265]
Currently the spin install script supplies a spin release version as an informational prompt for potentially downloading a specific version.  This version may drift from the actual latest Spin release (ref https://github.com/fermyon/developer/pull/264).

What would we like to do to prevent drift?

- Add release process notes to submit a PR a la #264 on each spin release
- Add automation for a bot to do ^^
- Remove the informational versions altogether
- Other?

**Comment by itowlson** [comment]
Dummy version a la `v1.2.3` would be another possibility

**Comment by tpmccallum** [comment]
I believe this is resolved by https://github.com/fermyon/developer/pull/264/files
Was thinking that we could run a command over the docs upon each release i.e. find ./ -type f -exec grep -H 'v0.6.0' {} \; to locate any references to older versions of Spin and then update.
If not, please let me know and we can discuss it further.
