### ISSUE TITLE
adjust menu layout for iPad layout

### ISSUE THREAD

**Issue by flynnduism** [fermyon/developer#277]
The top menu is squished when viewed at this size:

<img width="1096" alt="Screen Shot 2023-02-01 at 10 59 40 PM" src="https://user-images.githubusercontent.com/686194/216254274-d75ced86-9e4c-4e83-97bf-05c582d80848.png">

**Comment by tpmccallum** [comment]
Appears to be collapsing correctly now at `1036` x `1366`
![Screenshot 2023-03-28 at 1 21 18 pm](https://user-images.githubusercontent.com/9831342/228119442-f19672c3-c5ea-4a0d-ac98-23bdacf76859.png)
