### ISSUE TITLE
CLI reference for `spin` is only in the `cloud` section of the docs

### ISSUE THREAD

**Issue by mikkelhegn** [fermyon/developer#279]
The `spin` cli reference is only available in the TOC of the Cloud section. I'd love for it to also be available in the Spin section of the docs.

**Comment by tpmccallum** [comment]
Fixed by https://github.com/fermyon/developer/pull/285

We now have CLI reference resources (complete with appropriate template-based sidebar menu) in Spin and Cloud.
We now have doc contribution resources (complete with appropriate template-based sidebar menu) in Spin, Cloud and Bartholomew Docs
