### ISSUE TITLE
document how to expose HTTP triggers using HTTPS

### ISSUE THREAD

**Issue by mikkelhegn** [fermyon/developer#287]
See this Discord thread: https://discord.com/channels/926888690310053918/950022897160839248/1071051206954319872

**Comment by tpmccallum** [comment]
Started a new PR here; not by any means complete; I just need a little help getting this more accurate and relevant please.
https://github.com/fermyon/developer/pull/343

**Comment by tpmccallum** [comment]
This has been fixed on PR https://github.com/fermyon/developer/pull/383
