### ISSUE TITLE
Add a Stabilization Matrix for Spin

### ISSUE THREAD

**Issue by melissaklein24** [fermyon/developer#289]
Add a matrix to the documentation that shows the features as experimental or stable.

**Comment by tpmccallum** [comment]
@itowlson has created a really great prototype of this at https://gist.github.com/itowlson/cb1ff61d942e9cdf416471519fd97c40

This appeals to both Spin and Cloud and therefore should be in a central place (as apposed to just in Cloud docs or just in Spin docs). We are toying with the idea of having a central place for these sorts of common/reusable resources. See https://github.com/fermyon/developer/issues/291

**Comment by michelleN** [comment]
We've agreed on a few terms to use when describing stability: experimental, stabilizing, stable, deprecated.
I've added a stability table for the CLI to the developer docs here: https://github.com/fermyon/developer/pull/468
Another thing we could do is add a stability table for the host services available in spin and what their stability levels are. For example, this table is from @itowlson's gist:
| Host services                          | Stability | Maturity | Cloud |
|----------------------------------------|-----------|----------|-------|
| Outbound HTTP                          | Stable | Production  | Yes   |
| Outbound Redis                         | Stable | Production  | Yes   |
| Dynamic config                         | Beta | Dev | Limited |
| PostgreSQL                             | Beta | Dev | Yes |
| MySQL                                  | Beta | Dev | Yes |
| Key-value storage                      | Beta | Dev | No |

I think once we add a host services table, I'd be satisfied as marking this item as complete. What do ya'll think?

**Comment by michelleN** [comment]
| Host Capabilities/Interfaces (bikeshed open?)                          | Stability  | Cloud |
|----------------------------------------|----------|-------|
| HTTP                          | Stable   | Yes   |
| Redis                         | Stable   | Yes   |
| Outbound HTTP                          | Stable   | Yes   |
| Outbound Redis                         | Stable  | Yes   |
| Dynamic config                         | Experimental | Limited |
| PostgreSQL                             | Experimental | Yes |
| MySQL                                  | Experimental | Yes |
| Key-value storage                      | Stabilizing | No |

**Comment by tpmccallum** [comment]
Please see https://github.com/fermyon/developer/pull/491, which implements this update.
