### ISSUE TITLE
Spin install doc - default to new version and linux dependencies

### ISSUE THREAD

**Issue by mikkelhegn** [fermyon/developer#292]
This doc: https://developer.fermyon.com/spin/install

The first install command is tied to v0.8.0. The install script will take latest by default, so it can be made generic by using `curl -fsSL https://developer.fermyon.com/downloads/install.sh | bash -s`

I just installed a fresh Ubuntu machine, and it wasn't required to do the extra step described, to get a Go Spin component up and running.

**Comment by mikkelhegn** [comment]
@tpmccallum - just realized I missed this in a recent PR review, sorry about that!

**Comment by tpmccallum** [comment]
Hi @mikkelhegn 
Sorry I am not 100% sure what issue is being raised. Is this one ok to close?
If not please let me know what you would like changed and I will resolve asap.
Thanks so much
Tim

**Comment by mikkelhegn** [comment]
Sorry for the confusion :-)

You don't have to pass a specific version number to the install script to install latest
`curl -fsSL https://developer.fermyon.com/downloads/install.sh | bash` will do it. So the quicksstart can just always do that and not be tied to a version number.

**Comment by tpmccallum** [comment]
Thanks for clarifying @mikkelhegn 
I have a new PR which removes the version (unless, on a rare case, we are trying to demonstrate how to deliberately install a specific version)
https://github.com/fermyon/developer/pull/314

**Comment by tpmccallum** [comment]
I think it is safe to leave the Cargo install with a version number specified (otherwise the user gets the head of main; which is not necessarily ideal (pre-official point release in most cases).

**Comment by tpmccallum** [comment]
Fixed by https://github.com/fermyon/developer/pull/314/files
