### ISSUE TITLE
Add some document for installing spin on k8s

### ISSUE THREAD

**Issue by Patrick0308** [fermyon/developer#310]
Add some document for installing spin on k8s

**Comment by Patrick0308** [comment]
@itowlson I want to know how to install it now. Maybe I open another issue with a title of how to install spin on k8s?

**Comment by itowlson** [comment]
I assume you're thinking via the DeisLabs containerd shim?  @Mossaka and the DeisLabs folks have some info about the latter at https://github.com/deislabs/containerd-wasm-shims#example-kubernetes-cluster-deployments - does that help?

**Comment by Mossaka** [comment]
Hey @Patrick0308 ! Happy to help. In addition to @itowlson 's link, this [page](https://github.com/deislabs/containerd-wasm-shims/tree/main/deployments/k3d) gives you some instructions on trying out a quick "hello world" spin example on k3d cluster! Let me know if you have more questions and feel free to open an issue on the containerd-wasm-shims repo!

**Comment by Patrick0308** [comment]
@itowlson This seems more inefficient on k8s than not because we run http wasm code on a pod. And Pod can not scale to zero.

**Comment by tpmccallum** [comment]
I believe that @chrismatteson is well on the way towards making this documentation happen; as a new PR.
Will keep in touch.

**Comment by tpmccallum** [comment]
@chrismatteson has created new k8s documentation at https://developer.fermyon.com/spin/kubernetes
