### ISSUE TITLE
Document where curl-bash installs

### ISSUE THREAD

**Issue by technosophos** [fermyon/developer#318]
![Screenshot 2023-02-10 at 10 38 08 AM](https://user-images.githubusercontent.com/89193/218159056-472bc0d8-fa7c-48aa-8153-f2af1c5539f5.png)

The installation guide does not say where curl-bash installs. I expected `/usr/local/bin`, but it installed into the CWD. That's a totally fine place to put it, but we should document.

**Comment by technosophos** [comment]
Ah... now a note of clarification after reading the `macOS` instructions: It actually says this in the docs, but after the Linux guide shows some apt-get instructions. So maybe just clarifying it earlier would do the trick.

**Comment by tpmccallum** [comment]
Fixed by https://github.com/fermyon/developer/pull/335
