### ISSUE TITLE
Update all instances of the term `oci` to `registry` upon 0.9.0 release

### ISSUE THREAD

**Issue by tpmccallum** [fermyon/developer#325]
The term `oci` will be changed to `registry` so we need to run the following command across all developer docs when 0.9.0 ships.

```bash
find content/ -type f -exec grep -H 'oci' {} \;
```
Then create a new PR which replaces `oci` with `registry` (should only be a few instances)

**Comment by radu-matei** [comment]
For reference, `spin oci` commands will still work fow now, since we have an alias in place for `spin oci` -> `spin registry`.

**Comment by macolso** [comment]
hey @tpmccallum - i'm starting a PR that uses the code blocks for both v0.8.0 and v0.9.0, that way we can support both users

**Comment by macolso** [comment]
Its almost done - I was going to push it this afternoon

**Comment by macolso** [comment]
https://github.com/fermyon/developer/pull/346
