### ISSUE TITLE
CI/deploy for search index (data.json)

### ISSUE THREAD

**Issue by vdice** [fermyon/developer#369]
@karthik2804 and I were discussing the following pain point: Currently, this website's search index (`static/data.json`) needs to be updated in each applicable PR (any PRs updating documentation content, no matter how small, are applicable).  There is a command to do so (`npm run build-index`) and a note/reminder on the PR template, but it is still an extra step for contributors -- not to mention it introduces the common scenario of merge conflicts occuring to in-flight PRs as others are merged in.

Therefore, we'd like to find a solution where CI/automation does this chore work in the background, removing the need for contributor PRs to update this file (and eliminating the frequent merge conflict potential).

In brainstorming with @karthik2804, these are the top candidates that seemed preferable to some other scenarios discussed.

### Context

Currently, the website itself is published to bindle as a Spin app after cloning this repo at a configured branch and/or commit.  The live website consists of a `spin up --bindle-id` command using the published bindle ID.

### Publish/deploy from OCI registry reference

Added [below](https://github.com/fermyon/developer/issues/369#issuecomment-1444658594), bumped up to top potential candidate (bonus: dogfoods Spin's newly-added OCI reference support):

On every push to `main`, an automation agent (eg GH action) would clone the repo and run `npm run build-index`, then publish the website (Spin app) to an OCI registry (obvious choice: `ghcr.io/fermyon/developer`) via `spin registry push`.  We'd remove Bindle from the equation and the [website Nomad job](https://github.com/fermyon/developer/blob/main/deploy/fermyon-developer.nomad) would be updated to run from the pushed image reference, eg `spin up -f ghcr.io/fermyon/developer:<tag>`.  As the search index is commited in the form of an image, we'd `.gitignore` the file.

Considerations: To achieve parity with current deployment workflows, which allow for deploying from arbitrary branches/commits on the fermyon origin, we'd perhaps want to add publishing of images on PRs (again just for branches on the fermyon org).  Or, we could decide that ad hoc/out-of-band publishing by those with access to this repo's container registry is sufficient prior to non-main deploys.  For the default website image, we could use a mutable tag like `latest` that would be updated on every push to main.  Alternatively, we could follow the convention of using unique/"immutable" tags but would want to look into storage costs and/or automated cleanup.

Alternative:

### Deploy website from branch other than `main`

This retains current behavior of tracking the search index in git, albeit via a different branch from `main`.

On every push to `main`, an automation agent (eg GH action) would clone the repo and run `npm run build-index`.  To avoid churn from then having the agent push to main again (if so, we'd have one automation commit paired with every contributor commit to main), automation would push its changes to a separate branch, say, `deploy` (where `static/data.json` will still be tracked by git, as opposed to on `main` where we'd `.gitignore` it).

The website would then be deployed from the `deploy` branch, similar in spirit to the classic gh-pages approach.  The [deploy action](https://github.com/fermyon/developer/blob/main/.github/workflows/deploy.yml) would be updated to watch push events to this branch and the publish/website jobs would be updated similarly.

Thoughts/feedback @tpmccallum, others?

**Comment by vdice** [comment]
You know what, @karthik2804, we could also have the GH action publish the site to an OCI registry (obvious choice: ghcr.io/fermyon/developer) and then we could just remove bindle from the mix and update the website Nomad job to run from the reference, eg `spin up -f ghcr.io/fermyon/developer:<tag>`.  We wouldn't need a separate `deploy` branch as the data.json changes would only be committed in the form of said image.

**Comment by karthik2804** [comment]
That sounds like a good idea to me @vdice.

**Comment by vdice** [comment]
Thanks @karthik2804, I updated the original issue description w/ the OCI approach.  Added a note around your question (out-of-band) around deploying arbitrary branches/commits and potential storage costs of accrued OCI tags -- good points to raise.

**Comment by itowlson** [comment]
I would love to see this.  `data.json` is one of the banes of my life.

![image](https://user-images.githubusercontent.com/865538/222298410-20b29031-40e6-4f64-b0a6-21bab466f3f7.png)

**Comment by tpmccallum** [comment]
Is the "Deploy website from branch other than main" approach able to be implemented in the short term to trial?
I really like this idea.
@vdice @karthik2804 is there anything you need from me; testing/usage?
I think implementing a solution to the data.json file conflicts would be epic.

**Comment by vdice** [comment]
@tpmccallum I can revise https://github.com/fermyon/developer/pull/423 to allow deployments from branches other than main (which is possible today using the bindle-based approach, so it would be maintaining feature parity).

Apologies for having the draft PR sit so long.  To utilize [GHCR](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry), which is the most convenient container registry for this purpose, it being provided/paired to this self-same repo, we need a future release of the spin cli with its oci client updated (primarily to get concurrent pushes and pulls, so we don't time out attempting to push this Developer website app, what with its many layers of static assets).  @karthik2804 and I were talking about this today, actually, and we should be good to update the cli to use our fork of this oci library (see https://github.com/fermyon/oci-distribution).

Alternatively, we could utilize fermyon's DockerHub account and move this forward.  This would take a bit more config (eg passing in credentials for signing in to the registry) but certainly do-able.

While we mull over the preferred registry approach, I can update the draft PR with the changes mentioned in the first paragraph above...
