### ISSUE TITLE
Make v0.10.0 primary on OCI documentation page

### ISSUE THREAD

**Issue by rajatjindal** [fermyon/developer#387]
on https://developer.fermyon.com/spin/spin-oci, the primary version is `v0.8.0`, and we have to switch tabs to see `v0.9.0`. we should probably make v0.9.0 as primary.

cc @tpmccallum

**Comment by tpmccallum** [comment]
Thanks @rajatjindal 
As we have 0.10.0 coming out tomorrow, I have updated this issue to reference 0.10.0.

**Comment by tpmccallum** [comment]
Closed by https://github.com/fermyon/developer/pull/419
