### ISSUE TITLE
Preferred language

### ISSUE THREAD

**Issue by itowlson** [fermyon/developer#402]
If/as we move to multilingual pages with tabbed language examples, it would be good to remember the user's preferred language, either via a widget like the light/dark mode one, or by remembering the last language they selected.  The latter is more natural, but would need care that viewing an example where we had to fall back to another language didn't reset the selection.

**Comment by karthik2804** [comment]
We do remember user selection on languages now. I am not sure about the reset behavior but I believe that it does not auto-reset to a different language unless the user clicks a specific language.

**Comment by itowlson** [comment]
Doh!  Thanks!
