### ISSUE TITLE
Python highlighter outdents all but first line, and has scrollbar

### ISSUE THREAD

**Issue by itowlson** [fermyon/developer#407]
Source:

![image](https://user-images.githubusercontent.com/865538/222320301-da9da442-6dd9-456f-a61c-4278dc90ee79.png)

Display:

![image](https://user-images.githubusercontent.com/865538/222320353-d5b0765f-8bb3-4aff-a10e-4c64b561d57b.png)

It's not obvious from the screenshot, but the issue is not that the first line is _indented_ - the first line lines up with other code blocks on the page - but that subsequent lines are _outdented_.

Plus it gains the funny vertical scrollbar which doesn't seem to happen with other highlighters.

**Comment by karthik2804** [comment]
It is an issue due to our build of `highlight.js` not including the `python` module. It should be fixed with a newer build.

**Comment by karthik2804** [comment]
#408 fixes this.
