### ISSUE TITLE
Rework `spin.toml` reference in `configuration` article

### ISSUE THREAD

**Issue by mikkelhegn** [fermyon/developer#413]
To make the Spin manifest toml more accessible I'm proposing to rewrite this to a table format.

**Comment by tpmccallum** [comment]
The original `configuration` document has had some changes and now redirects to https://developer.fermyon.com/spin/writing-apps
Are the changes sufficient or does this re-write Re: using table format still need to happen?

**Comment by itowlson** [comment]
The table rewrite is live at https://developer.fermyon.com/spin/manifest-reference

**Comment by mikkelhegn** [comment]
@tpmccallum - I didn't notice if we linked from https://developer.fermyon.com/spin/writing-apps to https://developer.fermyon.com/spin/manifest-reference, if not that would be great.

**Comment by itowlson** [comment]
![image](https://user-images.githubusercontent.com/865538/234962672-265d5c10-79a1-48a6-88c6-1fa886b5da03.png)

**Comment by mikkelhegn** [comment]
I need to look more carefully :-)
