### ISSUE TITLE
Indent on first line of inline monospace block

### ISSUE THREAD

**Issue by itowlson** [fermyon/developer#414]
I have some inline monospaced elements, created in Markdown using single backtick and no embedded leading space.  For example:

![image](https://user-images.githubusercontent.com/865538/222562458-6e6b7155-064c-40f1-b37f-2be3a3770633.png)

When I render them on the docs site, they appear to have a leading space or small leading indent:

![image](https://user-images.githubusercontent.com/865538/222562055-02f83470-dede-4f33-bc45-489eca53f9ee.png)

Expected behaviour is that the first characters of each line would align vertically.

**Comment by karthik2804** [comment]
I am assuming that this is happening inside a table. In that case, we could have some CSS like 
```
table > code { display: block;}
```

to solve the issue.

**Comment by itowlson** [comment]
Correct, it is inside a table (and the column is narrow enough to cause the inline to wrap).

**Comment by karthik2804** [comment]
It can be fixed with CSS, although I am not sure the CSS I wrote above is correct. Have not tested it yet.
