### ISSUE TITLE
Comments in code blocks should be prominent, or at least visible

### ISSUE THREAD

**Issue by itowlson** [fermyon/developer#420]
I wrote a comment in this code block, to draw the reader's attention to the bit I wanted to highlight.

![image](https://user-images.githubusercontent.com/865538/222997811-75b7c6d3-36b0-4d4b-bf65-ef23ed83efdc.png)

But the comment is rendered as dark grey on black, making it very hard to see.

Comments aren't something that should be discreetly receded; _particularly_ in examples, they are there to point the reader at the most important bits.

**Comment by tpmccallum** [comment]
This would be a good one for a new contributor who wants to have a go at updating `.scss` files in the source code; which in turn generate new `.css` files. We have specific documentation at the following link
https://developer.fermyon.com/common/contributing-docs#63-how-to-properly-edit-css-styles
Also see this video on how to contribute to Fermyon technical docs. It will be great to see new faces collaborating on this open source project.
If you need help, please ask in the comments here.

**Comment by karthik2804** [comment]
It is a very straightforward fix. The class `hljs-comment` in 'style.scss` needs to be overridden with something like 

```scss
.hljs-comment {
  color: #a0a0a0;
}
```
Or potentially something even brighter. And while we are it do we also want to increase the font weight for comments? 
![image](https://user-images.githubusercontent.com/25023490/223594636-cdf1b6d0-77f4-4cdd-b259-12aca166c5a5.png)

**Comment by itowlson** [comment]
a0a0a0 was still a little grey for my taste but I think the other text already uses all the colours!  It is definitely better though!  Might be worth experimenting with a slightly brighter grey, see how people generally feel, but I'm happy to do with a0a0a0 if that's what other folks like.

**Comment by karthik2804** [comment]
My last comment was a bit more pointing out that it was a straightforward fix and also showing the increasing font-weight. I don't have any preference for a particular color, We could definitely make it brighter.

cc @flynnduism
