### ISSUE TITLE
Note text should not be bigger than surrounding text

### ISSUE THREAD

**Issue by itowlson** [fermyon/developer#421]
We use the Markdown block quote indicator, `>`, to represent notes or exceptions or remarks or other stuff that is relevant to the surrounding text but which we want to present out of flow.  The way we present this currently uses a slightly larger font and a distinctive colour, more like a pull quote for emphasis.  Here is an example from the "HTTP trigger" page:

![image](https://user-images.githubusercontent.com/865538/223015973-1a3962db-70e9-416b-962e-7e1453b117a2.png)

We should either:

* Make the 'quote' (note) text smaller in the developer docs, probably the same size and colour, and set apart by indent and background; or
* Use different markup for "notes" as opposed to pull quotes, like the blocks we have for tabs or something.  This would be more laborious, but would mean we could have specific styling for remarks, warnings, exceptions, and fun facts, using colour or icons or whatever.

Our solution should be conscious of how `fermyon.com` uses the `>` markup - as a more comms-centric site it may want to retain a pull quote feature.  Or it may not, I don't know, just saying we should be aware.

cc @tpmccallum @flynnduism

**Comment by karthik2804** [comment]
I like the specific markup idea! If we go down that route, I can create a PR that adds the markup that can allow us to have various classes for different types of sections.

One alternative solution would be to use a similar approach to what we have for copy button on code blocks by annotating content with HTML comments but that would possibly introduce unnecessary JS on the front end. The one upside though is that the `>` markup does not change, just would need HTML comments around.

**Comment by karthik2804** [comment]
@itowlson #428 seems to have addressed this, can we close this?

**Comment by itowlson** [comment]
Yep, closing, thanks!
