### ISSUE TITLE
Confusing page titles "Writing applications" and "Building Application Code"

### ISSUE THREAD

**Issue by radu-matei** [fermyon/developer#435]
I find the two pages to have rather confusing titles. I don't have a good suggestion on what to name them, or even if the "Building Application Code" section should exist (realizing I created the page a while back).

![image](https://user-images.githubusercontent.com/13103165/224012379-a61b81e6-1e1d-4575-9f75-c7676bbd8d5d.png)

**Comment by itowlson** [comment]
Yeah the one about `spin build` is a bit of an anachronism - it used to be called "Developing Spin Applications" but was all about the `build` command so I renamed it.  Though the fact that the TOC now sort of mirrors "new-build-up" (you may have to squint) is kind of nice.

Longer term, I would really like to break all this down into smaller topic-specific pages, at which point it should solve itself.

For now., one option is to fold it into the "writing" or "running" page, though that doesn't feel quite natural.

Another could be something like "Building Wasm Modules" or "The Spin Build Process" (though the latter sounds way too arcane).

@tpmccallum any suggestions for clearer titles?

**Comment by tpmccallum** [comment]
![Screenshot 2023-08-22 at 08 16 45](https://github.com/fermyon/developer/assets/9831342/d30c172f-7087-4d33-a038-0efab67abbaf)

I started with "Building Applications", and then it evolved to "Compiling Applications".
I asked ChatGPT and it introduced a new term I have not thought of which was "Generate". I guess technically we are always "Generating Binaries" when we run `spin build`. 

However, is this too low level and should we stick to the more general (yet ambiguous "building" or "compiling")?
