### ISSUE TITLE
"Hosting Spin Apps in Open Container Initiative (OCI) Registries" title is confusing

### ISSUE THREAD

**Issue by radu-matei** [fermyon/developer#436]
- the word "hosting" might suggest that you only need a registry to run the application, when in fact you need to `spin up`.
- we moved away from `oci` commands in the Spin CLI to avoid confusion with the name of a spec not a lot of people are familiar with, so I would not put the OCI acronym (or its expansion) in the page title

![image](https://user-images.githubusercontent.com/13103165/224012878-0b1a6ebc-84a4-41fe-ac15-a86c2958de76.png)

**Comment by tpmccallum** [comment]
Changes required to the following page
https://developer.fermyon.com/spin/spin-oci
