### ISSUE TITLE
Add a mention of `wasm32-wasi` target in cloud quickstart

### ISSUE THREAD

**Issue by karthik2804** [fermyon/developer#448]
There is no mention of the requirement of the `wasm32-wasi` target in the cloud quickstart.

https://discord.com/channels/926888690310053918/950022897160839248/1083871280018751589

**Comment by itowlson** [comment]
We should port the changes to the Spin quickstart across to Cloud.

**Comment by itowlson** [comment]
Okay, scratch that.  The Cloud quickstart uses a pre-build Wasm module.  It's the "develop a Spin application" page that needs updating.
