### ISSUE TITLE
edit on github link broken for manifest reference page

### ISSUE THREAD

**Issue by michelleN** [fermyon/developer#459]
The `edit on github` button at the bottom left of the [manifest reference](https://developer.fermyon.com/spin/manifest-reference.md) document seems to be broken. It is redirecting me to a link with an extra `.md` at the end: https://github.com/fermyon/developer/blob/main/content/spin/manifest-reference.md.md

**Comment by karthik2804** [comment]
@itowlson  Okay, this issue still exists. The issue is that the URL linked to is  https://developer.fermyon.com/spin/manifest-reference.md which includes the `.md` in the URL. That is what leads to the double `.md` at the end.

@michelleN, did you get directed to that link by some other link on the site or was it manually entered?

**Comment by itowlson** [comment]
Are you sure @karthik2804?  This is what the production site shows me for the Edit in GitHub button:

![image](https://user-images.githubusercontent.com/865538/225169847-c7fea13c-b66f-40b0-9eab-2f1d4b366b6d.png)

and the link appears to work correctly.

**Comment by karthik2804** [comment]
It does work correctly when navigated from the website but if it is accessed through https://developer.fermyon.com/spin/manifest-reference.md , then the trailing `.md` is added.

**Comment by itowlson** [comment]
Huh, the same is true for every page on the site, e.g. https://developer.fermyon.com/spin/install.md.  I don't know how that link is getting built...?

**Comment by itowlson** [comment]
@karthik2804 uh oh

https://developer.fermyon.com/spin/install.hello-karthik

**Comment by itowlson** [comment]
Unassigned myself because the remaining issue is no longer a content issue and I have no idea how to fix it I'm afraid!

**Comment by karthik2804** [comment]
It is generated using `spin-path-info`

**Comment by karthik2804** [comment]
I will fix that.
