### ISSUE TITLE
remove spin bindle command references 

### ISSUE THREAD

**Issue by michelleN** [fermyon/developer#478]
remove `spin bindle` command references once https://github.com/fermyon/spin/pull/1287 has merged

**Comment by vdice** [comment]
This will be addressed in https://github.com/fermyon/developer/pull/488

**Comment by vdice** [comment]
Now that https://github.com/fermyon/developer/pull/488 and https://github.com/fermyon/developer/pull/489 are in and deployed, we should be good to close.  Thanks for tracking @michelleN!
