### ISSUE TITLE
Quickstart page has two dead links at the bottom for the heading Next Steps

### ISSUE THREAD

**Issue by patterns** [fermyon/developer#481]
The [two "Learn" links](https://developer.fermyon.com/spin/quickstart/#next-steps) go to the not-found page while the third cloud link works. The sidebar nav has both destinations available and working (`/spin/writing-apps`, `/spin/build`) and inspecting the working cloud link in the raw file, it shows `/cloud/quickstart`  while the other two are relative.

**Comment by itowlson** [comment]
Sorry about this and thanks for letting us know; I see the same thing.

@tpmccallum @karthik2804 As far as I can tell, the links in `quickstart.md` are formatted in the same way as, say, `build.md`, but the latter work and the former don't.  They also work when running locally, which is why the link checker doesn't pick them up.  But on the production site they have the extra bit of path.  Any idea what could cause this?

**Comment by tpmccallum** [comment]
Thanks @patterns 
Will have this fixed asap.
https://github.com/fermyon/developer/pull/482/files

**Comment by karthik2804** [comment]
@itowlson I suspect this is some browser-specific behavior. It works as expected on chrome windows and android for me.

![image](https://user-images.githubusercontent.com/25023490/225809484-cc5866a2-dedf-413c-bc7f-64bfa7d003f0.png)

**Comment by itowlson** [comment]
Aha, that makes sense - I just tried `quickstart` and it suddenly fixed itself.

**Comment by karthik2804** [comment]
We should possibly not use relative URLs with the factor of a trailing slash existing.

**Comment by tpmccallum** [comment]
My understanding, whilst testing this, is that if a user is visiting a page and have a trailing slash in the URL i.e. `https://developer.fermyon.com/spin/quickstart/` (as opposed to no trailing slash i.e. `https://developer.fermyon.com/spin/quickstart`) then clicking relative URLs on that specific page will result in "Not Found" errors for the user.

@karthik2804 with your knowledge about this:
- Is the fix to always use absolute URLs in documentation? If so we will need to write something in the lint process that does not allow relative URLs in markdown files.
- Is the fix to update how Bartholomew processes relative URLs? (I think there might be an upcoming Bartholomew `.wasm` upgrade that covers this right?)

Many thanks
Tim

**Comment by itowlson** [comment]
Can we bump up the priority of the Bartholomew work please because using absolute URLs is not a solution.

![image](https://github.com/fermyon/developer/assets/865538/b6735823-5491-4ce8-89e8-3f5d652b01ea)

**Comment by tpmccallum** [comment]
Fixed by https://github.com/fermyon/developer/pull/616
