### ISSUE TITLE
Document `CGO_ENABLED=1` environment variable Re: Go components

### ISSUE THREAD

**Issue by tpmccallum** [fermyon/developer#520]
Since the Go SDK is built using CGO, it requires the CGO_ENABLED=1 environment variable to be set.

This should be updated in the documentation for Go components.

**Comment by tpmccallum** [comment]
This was in the Linear backlog (original source of issue/request is available at https://github.com/fermyon/developer/issues/222)

**Comment by souravsk** [comment]
Hey, @tpmccallum so have cloned the repo and made the changes that you asked for. this is how it looks if you want me to make any changes let me know.

![image](https://github.com/fermyon/developer/assets/33636054/eacf0782-b8bb-416b-a20c-c4234c9c498f)

I have highlighted the changes.

**Comment by itowlson** [comment]
@souravsk That looks fine - the only change I'd ask for is to not capitalise "environment variable".  You might also want to consider mentioning it in the Go language guide, though there isn't an obvious place to put it in there right now.

The best thing to do is to send a PR so we have a structured place to address any concerns or problems (if there are any, that is!).  Thanks!

**Comment by souravsk** [comment]
okay, I'm going to create a PR then we can discuss the changes.

**Comment by tpmccallum** [comment]
Thanks @souravsk I confirm that `CGO_ENABLED=0` produces the error below:

```console
$ spin build          
Building component http-go with `tinygo build -target=wasi -gc=leaking -no-debug -o main.wasm main.go`
# github.com/fermyon/spin/sdk/go/http
../go/pkg/mod/github.com/fermyon/spin/sdk/go@v1.4.1/http/http.go:101:9: undefined: get
../go/pkg/mod/github.com/fermyon/spin/sdk/go@v1.4.1/http/http.go:108:9: undefined: post
../go/pkg/mod/github.com/fermyon/spin/sdk/go@v1.4.1/http/http.go:115:9: undefined: send
Error: Build command for component http-go failed with status Exited(1)
```

And, then when `CGO_ENABLED=1` the application builds successfully:

```console
$ export CGO_ENABLED=1
$ echo $CGO_ENABLED   
1
$ spin build          
Building component http-go with `tinygo build -target=wasi -gc=leaking -no-debug -o main.wasm main.go`
Finished building all Spin components
```
