### ISSUE TITLE
Document `exclude_files` options in spin.toml

### ISSUE THREAD

**Issue by tpmccallum** [fermyon/developer#522]
Document `exclude_files` options in `spin.toml` as this seems to be missing on the docs. 

https://github.com/fermyon/spin/blob/8dfc4d6fbb31d624eb034f78640cb207bec1f682/crates/loader/src/local/config.rs#L103

**Comment by tpmccallum** [comment]
https://github.com/fermyon/developer/issues/522

**Comment by karthik2804** [comment]
It was resolved with https://github.com/fermyon/developer/pull/252

**Comment by itowlson** [comment]
@tpmccallum It is mentioned at both https://developer.fermyon.com/spin/writing-apps#including-files-with-components and https://developer.fermyon.com/spin/manifest-reference#the-component-tables... what's the background on this issue? do we need to mention it in other places too?

**Comment by tpmccallum** [comment]
I thought this was going to need additional documenting relating to Spin `watch`. This is not the case, so closing this one now. Thanks for pointing out the examples where the `exclude_files` is already documented.
