### ISSUE TITLE
Show Javascript example parsing HTTP body

### ISSUE THREAD

**Issue by fibonacci1729** [fermyon/developer#533]
A user in discord mentioned that it would be useful to demonstrate how to parse the HTTP body. I just looked at the docs and didn't see any example explicitly showcasing this.

**Comment by tpmccallum** [comment]
Thanks @fibonacci1729 !
Just listing the examples which @karthik2804 gave in Discord for future reference and making a note that the helper methods `.json()` and `.text()` should land in the next release of the JS Plugin.

Parsing body as text:

```javascript
let decoder = new TextDecoder()
let text = decoder.decode(request.body)
```

Parsing JSON

```javascript
let decoder = new TextDecoder()
let text = JSON.parse(decoder.decode(request.body))
```

**Comment by tpmccallum** [comment]
Closed by https://github.com/fermyon/developer/pull/536
