### ISSUE TITLE
Set a schedule for events slider - Spin community meeting & office hours events

### ISSUE THREAD

**Issue by tpmccallum** [fermyon/developer#535]
We will have repeat events such as Spin community meetings and office hours Q & A sessions. These will be live events that could do with a little promotion from the developer docs event slider.

Can we create a set of reoccurring events in the slider, that turn on and off based on publish and expiry date (once the dates/times) have been decided by the hosts of these new events? 

@karthik2804 @flynnduism does the slider work in a way that we can set and forget publish and expiry dates of events?

**Comment by flynnduism** [comment]
> Does the slider work in a way that we can set and forget publish and expiry dates of events?

Yes, if you look at the existing event markdown files, there is an expiration date setting that controls this. So you can set it and forget it.

**Comment by tpmccallum** [comment]
Currently use the markdown expiration date to set and forget the events.
