### ISSUE TITLE
Code blocks are not following text width

### ISSUE THREAD

**Issue by mikkelhegn** [fermyon/developer#54]
<img width="1189" alt="image" src="https://user-images.githubusercontent.com/12242001/195599370-38c568db-2c25-4af3-8c18-5fe48a06f030.png">

Looks like it should be fixed in the Fermyon Style sheet:

fermyon-type.scss

```
ul, ol, dl, p, blockquote {
        margin: 1.67rem 0;
        font-size: 1rem;
        max-width: 800px;
}

    pre {
        margin: 1.333rem 0;
        max-width: 100%; <-- should be 800px like the above
        position: relative;
    }
```

**Comment by tpmccallum** [comment]
See linear.app's Developer Docs team for more information.
