### ISSUE TITLE
[spin]: Contributing guide should point to `cargo fmt`

### ISSUE THREAD

**Issue by ThorstenHans** [fermyon/developer#552]
The "Contributing to Spin" guide should mention that contributors should run `cargo fmt` before creating a PR.

Background: Once the PR has been opened, a GH action kicks in which lints the entire code. The action will fail, if the code is not formatted correctly. 

Telling the contributors that they should `cargo fmt` their code could streamline the contributing experience.

**Comment by itowlson** [comment]
We should mention Clippy too

and probably take out the stuff about conventional commits, because we have never required that from contributors

**Comment by itowlson** [comment]
There is a mention of running `make test` there which does trigger a `make lint`.  But agree this is worth calling out explicitly.
