### ISSUE TITLE
Github Actions example for TypeScript fails with Error: Can't resolve 'ts-loader'

### ISSUE THREAD

**Issue by jasonwashburn** [fermyon/developer#563]
Updated issue description to avoid confusion...

Originally reported issue concerning the Python Github Actions example was reported in error, there was a mixup on my part that led me down a bit of a rabbit hole. However, on a positive note, during the course of testing proposed changes, I did come across what appears to be an actual issue with the TypeScript Github Actions example which fails for `Error: Can't resolve 'ts-loader'`.  One solution that seems to work is adding a step to run `npm install` to the action. However, TypeScript is not my area of expertise, so there may be a more eloquent/more appropriate solution?

---- Issue as originally reported below ----
While following the documentation [here](https://developer.fermyon.com/cloud/github-actions) to add a Github Actions deploy action for a Python component, I discovered that the pipeline fails due the wasm32-wasi target not being installed. I fixed it initially by adding an additional run step  to add it using rustup, but then noticed that the Rust example on the documentation had an additional step to install the Rust toolchain and wasm32-wasi target. Looks like the step was just erroneously left off the other language examples (Python, TypeScript, Go). 

I've confirmed the Python example works once the additional step is added.

**Comment by jasonwashburn** [comment]
Submitted PR #564.

Python Example has been tested, currently validating Go and TypeScript examples as well.

**Comment by rajatjindal** [comment]
Hi @jasonwashburn , thank you very much for taking out time to report this issue and submit the PR.

If I understand correctly, the `rust-toolchain` should not be required for `go/python/typescript` based projects. 

I just tried testing them using workflows here: https://github.com/rajatjindal/fermyon-actions-test/tree/main/.github/workflows

But there is a good chance I may be missing something here. could you please point me to an example where it was causing failure?

**Comment by jasonwashburn** [comment]
Hmm, well it seems I discovered this "error" early this morning while setting up an action on my new rust project, but using the python action since most of the stuff I do is in Python 🤦‍♂️. 

On a positive note though I suppose, I did run into an issue while testing my changes with the typescript example, I added the details to a comment on the PR. Link to example build failure here: https://github.com/jasonwashburn/spin-gha-test/actions/runs/4761067852

**Comment by jasonwashburn** [comment]
Updated #564, removed additions of Rust toolchain to Python, Go, and TS examples. Left proposed fix to TypeScript example.

**Comment by tpmccallum** [comment]
https://github.com/fermyon/developer/pull/564 merged.
Thanks @jasonwashburn
