### ISSUE TITLE
Check allowed_http_hosts operation

### ISSUE THREAD

**Issue by tpmccallum** [fermyon/developer#580]
Received feedback that "allowed_http_hosts did not work". 
Suggest running through the documentation about this feature without prior assumptions and see if there is something we can improve on.

**Comment by itowlson** [comment]
Is there any more detail on the way in which it failed?

**Comment by tpmccallum** [comment]
I have tested this via the instructions in the developer documentation. Unable to find fault with it.
<img width="1397" alt="Screenshot 2023-07-17 at 10 35 41 am" src="https://github.com/fermyon/developer/assets/9831342/42a08e05-1ecc-4332-93f6-089630e6cb21">
