### ISSUE TITLE
Document Redis provider for KV store

### ISSUE THREAD

**Issue by mikkelhegn** [fermyon/developer#582]
Ref: https://github.com/fermyon/spin/pull/1365 and https://discord.com/channels/926888690310053918/1024646765149950022/1101069848982859776

**Comment by itowlson** [comment]
I know you know this, but for clarity of record as the user there is asking about Cloud behaviour: the Redis KV provider is currently supported only on _local_ Spin.  The docs for this are at https://developer.fermyon.com/spin/dynamic-configuration#key-value-store-runtime-configuration, though we should add a link from the main KV page.

**Comment by mikkelhegn** [comment]
Cool - thanks for pointing that out. I tried to find this on the docs site, but a with a few search phrases, I did not succeed.

I would have expected to find this under a persistent storage, or dedicated KV Store article.
