### ISSUE TITLE
CI/deploy: Use ghcr.io?

### ISSUE THREAD

**Issue by vdice** [fermyon/developer#589]
With https://github.com/fermyon/developer/pull/588, the Developer website is published as an OCI image and deployed from the published reference, using docker.io as the registry.

We'd initially hoped to use ghcr.io as the experience is a bit more streamlined (can use stock action GITHUB_TOKEN, etc).

However, when testing, attempting to push the website Spin app (image) repeatedly led to rate limiting errors eg the following from https://github.com/vdice/developer/actions/runs/4892021649/jobs/8733252133:

```
Run spin registry push ghcr.io/vdice/developer:latest
Error: cannot push Spin application

Caused by:
    Server error: url https://ghcr.io/v2/vdice/developer/blobs/uploads/, code: 429, message: {"errors":[{"code":"TOOMANYREQUESTS","message":"retry-after: 10.4[8](https://github.com/vdice/developer/actions/runs/4892021649/jobs/8733252133#step:10:9)7765ms, allowed: 2000/minute"}]}
```

This same behavior was not encountered when pushing the app/image from my machine.

I had tried using: the stock GITHUB_TOKEN with correct permissions, a generated GitHub PAT, toggling the package as public, all in an attempt to avoid this rate limit, with no luck.

The OCI client library used by Spin [does allow configuration of concurrency for pushes/uploads](https://github.com/krustlet/oci-distribution/pull/72) which we could potentially harness -- but we'd need to wire that through as a Spin configuration.

**Comment by tpmccallum** [comment]
I believe this can be closed now that the developer documentation publishing process has been updated.
Please let me know if there are any issues outstanding.
