### ISSUE TITLE
Production site includes a link to localhost

### ISSUE THREAD

**Issue by itowlson** [fermyon/developer#603]
On the Spin Dynamic Configuration page:

![image](https://github.com/fermyon/developer/assets/865538/dc3e03e0-658a-4ce6-8ad2-42823d0d74e6)

**Comment by itowlson** [comment]
I swear despite my grumping about the absolute URLs thing I was not looking for this!  Just noticed it while editing the page!

**Comment by karthik2804** [comment]
We might need to take a look to see if we are linking to localhost elsewhere as well. 

https://github.com/fermyon/developer/blob/d8f0d2a8a65731fe89a28165c7ec2055a4881360/content/spin/dynamic-configuration.md?plain=1#LL154C188-L154C265

**Comment by karthik2804** [comment]
That seems to be the only such instance.

**Comment by tpmccallum** [comment]
Fexed by https://github.com/fermyon/developer/pull/616/commits/c540f8005ad84696e1150f44a5b461966505bf03
