### ISSUE TITLE
Document Azure CosmosDB implementation for KV

### ISSUE THREAD

**Issue by tpmccallum** [fermyon/developer#611]
Update documentation to reflect the following merged PR
https://github.com/fermyon/spin/pull/1463

**Comment by tpmccallum** [comment]
Hi @kate-goldenring 
This documentation is going to take a while longer than expected.
You covered the critical message Regarding: config, as far as I can see inside the blog, which is excellent.
In addition, we are going to have to restructure the developer documentation slightly to accommodate these new docs:
- The https://developer.fermyon.com/spin/kv-store-api-guide is probably too general for this specific Azure implementation
- The https://developer.fermyon.com/spin/kv-store-tutorial page's menu and page title both highlight "Persistent Data Locally With Key Value Store". Whereas this is not stored locally. It might be the case that this is where the Azure docs live, but we will have to update the page title and menu and reword some of the contents.
- The https://developer.fermyon.com/spin/dynamic-configuration#key-value-store-runtime-configuration is another option; because it gives the example of customizing the `key_value_store.default.type`. Perhaps Azure example config can go alongside Redis example that is already there.
- There is one other option, and that is to move the `cloud/data-redis` and `/cloud/data-postgres` from Cloud back over to Spin and then create a new page at `/spin/data-azure`. The we would have `cloud/data-redis`, `/cloud/data-postgres` and `/spin/data-azure` alongside each other. (The only information in those cloud data examples is the `deploy` command. So technically they are not 100% cloud; they can also be run on Spin and probably belong in Spin to be technically accurate.)

It would be good to get some internal feedback about this.

**Comment by tpmccallum** [comment]
The equivalent of what is available for Redis (in the dynamic configuration docs) has been created at https://github.com/fermyon/developer/pull/648

The above points can still be actioned over and above this starter work.

**Comment by itowlson** [comment]
The Cloud pages mentioned are specifically for the BYO, database-specific interfaces.  We need a consistent way to talk about BYO backends for the "magic built in" interface (when those backends are no longer built in... and therefore don't work in Cloud... but the BYO interfaces do... _head spins_).

But agree we could still usefully port them to Spin - you're 100% correct that they're not specific to Cloud.

**Comment by kate-goldenring** [comment]
@tpmccallum I like the idea of removing "local/ly" from the tutorial as it is highlighting the ability to persist data and it happens to be local, a choice that could be swapped with the runtime config.

I also agree that all other persistence options (at least for KV) should live next to each other in Spin. For the setting values on deploy, that can be a call out to the deploy SDK as setting kvs on deploy is not a requirement to getting the most out of kv in the cloud

**Comment by tpmccallum** [comment]
https://developer.fermyon.com/spin/v2/dynamic-configuration
![Screenshot 2023-12-12 at 16 18 25](https://github.com/fermyon/developer/assets/9831342/83d2b5a9-f975-4a60-83e1-cff3d4ba2652)
