### ISSUE TITLE
Update documentation in accordance with the new `cloud` plugin

### ISSUE THREAD

**Issue by kate-goldenring** [fermyon/developer#621]
Add documentation on how Fermyon Cloud related commands are a part of a `cloud` plugin that is either automatically installed via the install script (todo), distributed with Spin via a package manager, or installed in the first invocation of `spin cloud` (or aliased `spin login` or `spin deploy`):

```sh
$ spin deploy
The `cloud` plugin is required. Installing now.
Plugin 'cloud' was installed successfully!
Uploading cloud_start version 0.1.0+XXXXXXXX...
Deploying...
Waiting for application to become ready... ready
Available Routes:
  cloud-start: https://cloud-start-xxxxxxxx.fermyon.app/ (wildcard)
```

Here is the current PR to move to using the plugin: https://github.com/fermyon/spin/pull/1452

cc @tpmccallum

**Comment by tpmccallum** [comment]
Thanks @kate-goldenring I will take a look.

**Comment by kate-goldenring** [comment]
looks like `spin doctor` was added so ill add a section on that

**Comment by itowlson** [comment]
`spin doctor` is hidden in 1.2.  It got merged into main so a wider group can iterate on it, but is not yet surfaced to users and should not be included in 1.2 docs.

**Comment by kate-goldenring** [comment]
sorry i meant to add this comment to the release blog -- will start a thread there

**Comment by itowlson** [comment]
@kate-goldenring Closing as you did this in a couple of PRs around the 1.3 timeframe - feel free to reopen if there is more to do!
