### ISSUE TITLE
Error in `bart check content/* && bart check content/**/*` part of build

### ISSUE THREAD

**Issue by tpmccallum** [fermyon/developer#629]
The build for developer documentation producing an error in the `bart check content/* && bart check content/**/*` command. This is a new error.

❌ content/robots.md	Document seems to be missing title. Is there TOML metadata?

![Screenshot 2023-05-17 at 3 21 58 pm](https://github.com/fermyon/developer/assets/9831342/96ed8acb-7391-47ae-b457-e3c8587120dd)

**Comment by karthik2804** [comment]
closed by #622
