### ISSUE TITLE
Inform plugin authors about available environment variables

### ISSUE THREAD

**Issue by kate-goldenring** [fermyon/developer#632]
We should update the [plugin authoring docs](https://developer.fermyon.com/spin/plugin-authoring#authoring-a-spin-plugin) to inform that the following environment variables (with example values) are set by spin in the plugin child process:
```sh
SPIN_BIN_PATH=/Users/cardoso/.cargo/bin/spin
SPIN_BRANCH=feat/more_build_info
SPIN_BUILD_DATE=2023-05-15
SPIN_COMMIT_DATE=2023-05-15
SPIN_COMMIT_SHA=49fb11b
SPIN_DEBUG=false
SPIN_TARGET_TRIPLE=aarch64-apple-darwin
SPIN_VERSION=1.2.0-pre0
SPIN_VERSION_MAJOR=1
SPIN_VERSION_MINOR=2
SPIN_VERSION_PRE=pre0
```

**Comment by itowlson** [comment]
I think it missed the 1.2 cutoff (by a couple of hours!), so don't merge the docs until the 1.3 batch.
