### ISSUE TITLE
Document SDK Reference for all supported languages

### ISSUE THREAD

**Issue by tpmccallum** [fermyon/developer#636]
We have a Spin CLI Reference; the next priority is a language-specific reference. Sometimes, this kind of documentation can be generated straight from the language.

At present, it would be great to prioritise Javascript and Rust (with Python etc., to follow).

cc: @mikkelhegn 

Just tagging a couple of engineers for ideas on if we can automate this or manually export API from the language and shoehorn that information into a developer documentation `.md` file.
@karthik2804 - Javascript?

@bacongobbler - Rust?

**Comment by tpmccallum** [comment]
**Rust:**
We could link to https://fermyon.github.io/rust-docs/spin/main/spin_sdk/index.html in the developer documentation; to resolve the Rust part of that issue?
Or we could export those docs as markdown/HTML and embedded in the developer docmentation site?
The latter would require regular syncing, so perhaps the former will suffice.
Thoughts?

**Javascript:**
T.B.D.

**Python:**
T.B.D.

**Go:**
T.B.D.

**Comment by mikkelhegn** [comment]
For Rust, that seems like a good option. Would like to see it in an official docs site also, like: https://docs.rs/spin-sdk/0.0.0/spin_sdk/. But I believe there's a reason why we're not publishing this to crates.io. @lann might know?

**Comment by lann** [comment]
We can't publish `spin-sdk` because we depend on the unpublished `wit-bindgen-rust` version `0.2.0`, and crates.io requires all published package dependencies to also be published.

That could be fixed, either by:
- Upgrading to a newer `wit-bindgen`, which will happen "eventually" (probably not until we go fully "component native" @dicej)
- Forking `wit-bindgen-rust` into e.g. `spin-wit-bindgen-rust`, publishing the fork, and switch our dependency to that

**Comment by lann** [comment]
Meanwhile, we have been (quietly) publishing rust docs for spin-sdk: https://fermyon.github.io/rust-docs/spin/v1.2.1/spin_sdk/

**Comment by dicej** [comment]
The current plan is to upgrade to the latest `wit-bindgen` for Spin 1.4.  That upgrade doesn't need to wait for the "component native" transition since we'll still be generating core modules, i.e. leaving the `wit-component` step until `spin up` time.

**Comment by tpmccallum** [comment]
We now reference SDKs for languages and have made this reference link more prominent
https://github.com/fermyon/developer/pull/1096
