### ISSUE TITLE
Dynamic templating seems to have stopped working

### ISSUE THREAD

**Issue by tpmccallum** [fermyon/developer#651]
If a user is on https://developer.fermyon.com/spin/index
and clicks "References"-> "CLI Reference"
they end up at https://developer.fermyon.com/common/cli-reference with the `common` menu (instead of the `spin` menu)

**Comment by tpmccallum** [comment]
Bartholomew PR addresses this
https://github.com/fermyon/bartholomew/pull/168

**Comment by tpmccallum** [comment]
From the implementation point of view, this is a list of tasks needed to implement this in developer docs:
- [ ] update the frontmatter of each file without a body
- [ ] create the canonical page that contains the body (that is linked to from the other body-less files)
- [ ] update the developer documentation's spin.toml file to remove any existing redirects (in relation to common files)
- [ ] check that pages are indexed by the web crawlers

Please add any more items to this list if you think of any.

**Comment by karthik2804** [comment]
closed by upgrade to bartholomew v0.8.0
