### ISSUE TITLE
How do I update all the Spin things?

### ISSUE THREAD

**Issue by technosophos** [fermyon/developer#653]
I am upgrading from Spin 1.0 to Spin 1.2.1, and the documentation doesn't tell me how to do this. It is not clear from the installation and quickstart guides how I should update all the things I have installed.

* Is there anything special I need to do to update Spin itself other than curl-bash it?
* How do I update all of my installed templates?
* How to I update all of my plugins? Is `spin plugin update` doing that? 
* Is there anything else I need to update to make sure my updated Spin installation is ready to use?

**Comment by tpmccallum** [comment]
Thanks, @technosophos 
This has been on our radar. Whilst there is the documentation for [upgrading templates](https://developer.fermyon.com/spin/managing-templates#upgrading-templates) and [upgrading plugins](https://developer.fermyon.com/spin/managing-plugins#upgrading-plugins) this far, we need a new page that explains the overarching update/upgrade process of Spin itself. And another new page that describes how to update an existing Spin application (i.e. ensure that the latest SDK is being used in that specific application).

**Comment by technosophos** [comment]
Yeah, that all makes sense. When I did my upgrade, I wasn't sure where else to go besides the install docs.

**Comment by tpmccallum** [comment]
Closed by https://github.com/fermyon/developer/pull/659
