### ISSUE TITLE
Go reference image in code block is wrongly formatted

### ISSUE THREAD

**Issue by mikkelhegn** [fermyon/developer#679]
<img width="886" alt="image" src="https://github.com/fermyon/developer/assets/12242001/c7acb654-d178-464d-b154-08d1ddb33745">

From: https://developer.fermyon.com/spin/kv-store-api-guide?_gl=1*1i5ezwn*_ga*MTkwMzc5MjEwNC4xNjc5MzM4NTA3*_ga_DXM7W0VBXS*MTY4NjEyMzAxNC4xNS4xLjE2ODYxMjMwMTguNTYuMC4w

**Comment by karthik2804** [comment]
I wonder why we are using an image there. Is that intentional?

**Comment by itowlson** [comment]
Other API guides just link to the GitHub package URL without using the badge or the proxy URL.  If our other Go docs are also on the proxy, I suggest we consistently link the proxy URL (as it provides formatted docs) but not the badge.  If that's okay I can update across the guides.
