### ISSUE TITLE
Python Outbound HTTP example throws an error

### ISSUE THREAD

**Issue by sohanmaheshwar** [fermyon/developer#692]
EDIT:

This code snippet works: 

```
from spin_http import Request, Response, http_send


def handle_request(request):

    response = http_send(
        Request("GET", "https://random-data-api.fermyon.app/animals/json", {}, None))

    return Response(200,
                    {"content-type": "text/plain"},
                    bytes(f"Here is a dog fact: {str(response.body, 'utf-8')}", "utf-8"))
```

Hello

The code snippet in the [Outbound HTTP Python example](https://developer.fermyon.com/spin/python-components#an-outbound-http-example) throws the error: 

`Handler returned an error: TypeError: argument 'headers': 'list' object cannot be converted to 'PyDict'`

I tried fixing it with these two code snippets to convert to dictionary but I got the same error:

```
from spin_http import Request, Response, http_send

def handle_request(request):
    response = http_send(Request("GET", "https://random-data-api.fermyon.app/animals/json", [], None))
    return Response(200,
                    dict([("content-type", "text/plain")]),
                    bytes(f"Here is an animal fact: {str(response.body, 'utf-8')}", "utf-8"))
```

```
from spin_http import Request, Response, http_send

def handle_request(request):
    response = http_send(Request("GET", "https://random-data-api.fermyon.app/animals/json", [], None))
    return Response(200,
                    [("content-type", "text/plain")],
                    bytes(f"Here is an animal fact: {str(response.body, 'utf-8')}", "utf-8"))

```

I also tried the code snippet in[ our Github](https://github.com/fermyon/spin-python-sdk/blob/main/examples/outbound_http/app.py) but the API linked here seems offline.

Wasn't able to debug the original code snippet so creating an issue for help.

**Comment by mikkelhegn** [comment]
@sohanmaheshwar - can this be closed?

**Comment by sohanmaheshwar** [comment]
Fixed both.

Docs: https://github.com/fermyon/developer/pull/693
Github sample: https://github.com/fermyon/spin-python-sdk/pull/36
