### ISSUE TITLE
Error rendering markdown: Error rendering "Unnamed template" Helper not defined: "tabs"

### ISSUE THREAD

**Issue by tpmccallum** [fermyon/developer#715]
There is an error being returned from `bart check` which I am unsure about. The error talks about a helper for `tabs` not being defined i.e. `Error rendering markdown: Error rendering "Unnamed template" line 71, col 1: Helper not defined: "tabs"`

Please see an example of the error and also the markdown to which it refers. Is this something that needs updating in Bartholomew itself? If so we can create another ticket/issue to resolve this in the next Bartholomew release perhaps.

<img width="1174" alt="Screenshot 2023-07-03 at 11 15 49 am" src="https://github.com/fermyon/developer/assets/9831342/39b55fc6-bc7c-44cb-a99e-f471951656b0">

![Screenshot 2023-07-03 at 11 16 05 am](https://github.com/fermyon/developer/assets/9831342/ff9bde7d-d459-45a5-a0ee-9a4e4ee462d6)

**Comment by tpmccallum** [comment]
I think we can rule out `|` and/or tables in markdown as being the issue, because other pages i.e. `api-guides-overview.md` does not raise the same issue via `bart check`.

<img width="1007" alt="Screenshot 2023-07-03 at 11 49 18 am" src="https://github.com/fermyon/developer/assets/9831342/e5639cc8-ea0c-4aca-99e7-b43a47923ba5">

![Screenshot 2023-07-03 at 11 49 04 am](https://github.com/fermyon/developer/assets/9831342/374e7b26-f986-4590-8860-349b594a7d3f)

**Comment by tpmccallum** [comment]
Running `bart check content/spin/* ` shows that there are several other files that also have the `tabs` issue.
Not sure what the common ground is between them at this stage (some error line numbers point inside code blocks etc.)
Would be interested to learn what is causing this ...

**Comment by itowlson** [comment]
Every file with a `{{ tabs }}` or `{{ details }}` block in it emits the "helper not defined" error (for whichever it first encounters I guess) but then green ticks anyway.

I tried older versions of `bart` and older versions of the site to see if there was a recent commit that started this happening, but it seems to have been producing these errors for at least 2 months (I didn't look further back).  Not sure if I am doing something wrong, though, I'd have expected us to notice it earlier if it really was happening all that time...

**Comment by itowlson** [comment]
If you add 8 to the line number in the error message then you get a `{{ tabs }}` or `{{ details }}` block in the Markdown.  I think this is the size of the Bartholomew page header (the title / date / URL stuff) i.e. the error line is counting from the start of the page _content_.

**Comment by karthik2804** [comment]
The issue is that bart does not know where to find the shortcodes. There is a cli flag on `bart` to pass the folder. That should solve this issue.  I'm currently outside. I can fix it tomorrow.

**Comment by tpmccallum** [comment]
Thanks @karthik2804 
To clarify we are only producing the error message by running `bart check` on **localhost**. I have not noticed any issues in GH workflows etc. (Just FYI).
If I just update the developer documentation to include the `--shortcodes` flag will that be enough of a fix? I tried it locally and the error disappears :) 

Is there anything more that needs to be done (just trying to imagine what additional fix could be applied)? You mentioned a fix in your previous message.

**Comment by tpmccallum** [comment]
Were you thinking of a fix along the lines of `bart` itself trying the default of `.shortcodes` directory without the user needing to provide the `--shortcodes` flag under normal operating conditions? Just curious.
Thanks so much for your help!

**Comment by karthik2804** [comment]
I was not talking about bart reading a default shortcodes directory as I think that would error out when it does not exist. I think it's safer for the cli flag to be added to the ci script.

**Comment by tpmccallum** [comment]
Thanks @karthik2804 
The caveat is that the tests do always pass (even when this error text is displayed as part of the `bart check` output).

You can go ahead with the work that will see the CLI flag added to the CI script; thanks. It certainly cant hurt.

From a localhost perspective (which is where the original error surfaced and why I created this issue) I have [tweaked the developer documentation](https://github.com/fermyon/developer/pull/719) to inform users of the shortcodes flag; just to be on the safe side (to avoid confusion). After all, a user who has the bart CLI kinda needs to point to the shortcodes directory themself.
