### ISSUE TITLE
Update the AKS runtime class to 0.5.1 to use v1.0 Spin

### ISSUE THREAD

**Issue by Mossaka** [fermyon/developer#730]
I notice that in this [article](https://developer.fermyon.com/spin/kubernetes), it uses the `wasmtime-spin-v1` runtime class to refer to the AKS node's runtime handler. However, this runtime handler is using a older version of Spin `v0.3.0`. I would recommend to this to `wasmtime-spin-v0-5-1` which uses the `v0.5.1` spin shim binary that uses `v1.0` spin.

**Comment by itowlson** [comment]
@Mossaka just to double-check, `v0.5.1` reads as an _earlier_ version than `v1`, but it does use the _later_ Spin version, right?

**Comment by Mossaka** [comment]
Yeah, `v1` is introduced when we didn't have a version proposal like [this](https://github.com/deislabs/containerd-wasm-shims/blob/main/proposals/2022-09-14-kubernetes-versioning.md). It is actually mapping to `v0.3.0` version of the spin shim. `v0.5.1` is using the later spin version.

**Comment by davidgamero** [comment]
I added this text, lmk any suggestions

> The RuntimeClass `wasmtime-spin-v0-5-1` on Azure maps to spin v1.0.0, and the `wasmtime-spin-v1` RuntimeClass uses an older shim corresponding to v0.3.0 spin.

**Comment by tpmccallum** [comment]
Hi @Mossaka 
Thanks for your input and contribution. Seeing how https://github.com/fermyon/developer/pull/738 is merged, can we close this 730 issue?

If not, please let us know and we will follow up to make sure that you are satisfied with the outcome.

I think this is ok to close, so if I don't hear back after a week I will just go ahead and close.
Thanks so much.

**Comment by Mossaka** [comment]
Sure you can close it

**Comment by tpmccallum** [comment]
Thank you, chat again soon :)
