### ISSUE TITLE
curl installer errors on step 2

### ISSUE THREAD

**Issue by flynnduism** [fermyon/developer#748]
@taylols and I hit this error when installing Spin 1.4 via the doc's curl installer:`curl -fsSL https://developer.fermyon.com/downloads/install.sh | bash`

**Error message:**

```
Step 1: Downloading: https://github.com/fermyon/spin/releases/download/v1.4.1/spin-v1.4.1-macos-aarch64.tar.gz
Done...

Step 2: Decompressing: spin-v1.4.1-macos-aarch64.tar.gz
x crt.pem
x spin.sig
x README.md
x LICENSE
x spin: Can't replace existing directory with non-directory
tar: Error exit delayed from previous errors.
```

The error was confusing - there was no previous `spin-v1.4.1-macos-aarch64.tar.gz` in the directory in question so this conflict was hard to understand.

**Workaround:** 

* deleted the downloaded `tar.gz` and extracted files (to ensure no conflict) and tried again - ❌ same error
* create a new subdirectory, run the curl installer inside there ✅ it works!

**Suggestions:**

* Not sure what prompted the directory error, but if it's common perhaps the Install docs could include a `mkdir spin && cd spin` precursor step?
* Or save that kind of instruction to be contextual in response to the installer CLI exiting with `Can't replace existing directory with non-directory`?
* This kind of thing could be documented under our [Troubleshooting](https://developer.fermyon.com/spin/troubleshooting-application-dev) section - searching w/ the error message provided no answers

**Comment by tpmccallum** [comment]
I finally got this same message today @flynnduism and @itowlson 
Essentially, the message arises when there is a `spin` folder in the working path that `curl -fsSL https://developer.fermyon.com/downloads/install.sh | bash` is being run. For example:

```
$ curl -fsSL https://developer.fermyon.com/downloads/install.sh | bash
Step 1: Downloading: https://github.com/fermyon/spin/releases/download/v1.5.0/spin-v1.5.0-macos-amd64.tar.gz
Done...

Step 2: Decompressing: spin-v1.5.0-macos-amd64.tar.gz
x crt.pem
x spin.sig
x README.md
x LICENSE
x spin: Can't replace existing directory with non-directory
tar: Error exit delayed from previous errors.

```

Decision, should we:
-  [ ] add a message in the docs for users to remove the `spin` directory first (before using the installer)
-  [ ] update the error message in the Spin CLI (which means that we need to move this issue back over to Spin project itself)
cc: @mikkelhegn

**Comment by itowlson** [comment]
@tpmccallum The Spin CLI can't do anything about this - it happens before the Spin CLI has even landed on disk (during unpacking of the tarball).  It can only be addressed in the installer.

(The message prefixed `spin:` is not _from_ Spin; it's _about_ the `spin` file.)

**Comment by tpmccallum** [comment]
Thanks @itowlson 
Have added a fix in the installer, please feel free to approve and we can close this one out.
