### ISSUE TITLE
Spin Up Hub entry modal

### ISSUE THREAD

**Issue by radu-matei** [fermyon/developer#771]
Not sure if these are on the radar, but thought I should report:

- the URL is not clickable
- the submitter should be a link to GitHub(?)
- the timestamp is not human readable

<img width="399" alt="image" src="https://github.com/fermyon/developer/assets/13103165/d7732cc0-b188-44b7-a7bf-caf74eb367eb">

**Comment by tpmccallum** [comment]
Thanks @radu-matei we will look at this very soon.

**Comment by karthik2804** [comment]
These have been fixed
