### ISSUE TITLE
Containerd configuration.

### ISSUE THREAD

**Issue by casperyap** [fermyon/developer#776]
For the documentation on Spin on Kubernetes => Setup Generic Kubernetes => config.toml, it states to add the following lines:

  [plugins.cri.containerd.runtimes.spin]
    runtime_type = "io.containerd.spin.v1"

It does not work for my K8s 1.27.2 setup. Instead, the following seems to work: 

  [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.spin]
          runtime_type = "io.containerd.spin.v1"

Besides, it is not clear where to add the above lines.

**Comment by tpmccallum** [comment]
Thanks @chrismatteson and @jpflueger 
This is closed by https://github.com/fermyon/developer/pull/795
