### ISSUE TITLE
Broken links - failing build

### ISSUE THREAD

**Issue by mikkelhegn** [fermyon/developer#781]
Looks like this is a broken link  https://docs.sigstore.dev/cosign/installation/. It is not related to this PR but it is broken on main I think. 

The `https://www.godaddy.com` link is a 403 and I tested that it fails with curl locally but the website works normally so we need to add it to our exceptions list. 
https://github.com/fermyon/developer/blob/c5700c969353479f7440c77acc35931f8e09a781/.build/check-broken-links.sh#L75

cc: @mikkelhegn

_Originally posted by @karthik2804 in https://github.com/fermyon/developer/issues/778#issuecomment-1677957409_

**Comment by tpmccallum** [comment]
Closed by https://github.com/fermyon/developer/pull/782
