### ISSUE TITLE
TS docs suggest using Redis for K/V and don't link to regular K/V

### ISSUE THREAD

**Issue by technosophos** [fermyon/developer#785]
I went to the JS/TS language guide to write a new Spin app. The KV storage section shows using Redis, but doesn't even say that I can use built-in K/V storage:

https://developer.fermyon.com/spin/javascript-components#storing-data-in-redis-from-jsts-components

It also doesn't indicate that I can use SQL storage.

This leaves the impression that KV and SQL are not supported in TS.

**Comment by tpmccallum** [comment]
Thanks @technosophos
