### ISSUE TITLE
JSON-stringifying a JavaScript error gives an empty object

### ISSUE THREAD

**Issue by macolso** [fermyon/developer#788]
Would be good to add this callout to JS API guide for SQLite: https://developer.fermyon.com/spin/sqlite-api-guide

**Comment by itowlson** [comment]
@macolso I renamed the issue to reflect the user impact, and that (from what @karthik2804 has indicated to me) this is part of the JavaScript error standard and is not specific to Spin SQLite errors.  Feel free to revert or further edit the title if you don't like it!

This does kind of raise a question about how much it is our job to document language/runtime surprises.  I can reproduce the exact same behaviour in plain ol' Node and plain ol' JS.  If the Spin docs take on the job of warning users about all the surprises in JavaScript then we could be here for a while...!

**Comment by tpmccallum** [comment]
Good point @itowlson 
However, we could add just a small note on the last line of the general notes in the Typescript tab (see image below).
All of the error I induce are actually surfaced as exceptions both in the Spin CLI and returned in the response.
What code can you suggest to break the following `index.js` so I can see the empty object (in place of a real error)?

```javascript
import {Sqlite} from "@fermyon/spin-sdk"
const encoder = new TextEncoder()

export async function handleRequest(request) {
    const conn = Sqlite.openDefault();
    const result = conn.execute("SELECT * FROM character;");
    const json = JSON.stringify(result.rows);
    
    return {
        status: 200,
        headers: { "foo": "bar" },
        body: encoder.encode(json).buffer
    }
}
```
![Screenshot 2023-08-18 at 11 59 21](https://github.com/fermyon/developer/assets/9831342/1580c067-eef1-4c96-863c-3ec146302fc7)

**Comment by itowlson** [comment]
@tpmccallum To see the issue, add this anywhere before the final `return`: 

```
try {
  throw new Error("oh no");
} catch (err) {
  const errjson = JSON.stringify(err);
  console.log(errjson);
  return { status: 200, headers: {}, body: encoder.encode(errjson).buffer };
}
```

**Comment by itowlson** [comment]
Or if you want to see the same effect being generated from the Spin SDK, change the SQL statement to `SELECT * FROM characterzzzzzzzzzzzz` and put it in a try-catch.

(Without the try-catch the unhandled error will be stringised and returned in the HTTP response, which is what you're seeing when you see error responses.  To see the JSON problem you have to `catch` the exception and `JSON.stringify` that.)

Note that because this is a JavaScript behaviour, not to do with Spin or SQLite, if we add the warning to one set of JS docs, we would want to add it to _all_ JS docs.

**Comment by tpmccallum** [comment]
Thanks I guess we don't want to add JavaScript behaviour in our docs (if it is not Spin related). I am however happy to add a single sentence just in case folks get an empty object and think Spin or Cloud is broken. It will be short and to the point; I promise :)

**Comment by tpmccallum** [comment]
Hi @macolso 
The following which both mention error handing have been updated.
Thanks @itowlson for all of today's reviews!!!
https://github.com/fermyon/developer/pull/794
https://github.com/fermyon/developer/pull/791
