### ISSUE TITLE
Create JS TS key-value store template example

### ISSUE THREAD

**Issue by tpmccallum** [fermyon/developer#792]
The TypeScript tab of [this documentation](https://developer.fermyon.com/spin/kv-store-tutorial#creating-a-new-spin-application) currently has [this spin-kv-ts](https://github.com/karthik2804/spin-kv-ts) which is in @karthik2804 's personal repo.

Can @karthik2804 please move this code alongside the [similar examples](https://github.com/fermyon/spin/tree/main/examples) in the Spin repo? Or can @karthik2804 please create a new `spin-kv-ts` Spin Up Hub (SUH) template and add it to our collection of SUH templates at https://github.com/fermyon/spin-js-sdk/tree/main/templates?

The end result (goal) being that we have an example for [this documentation](https://developer.fermyon.com/spin/kv-store-tutorial#creating-a-new-spin-application) which is in a Fermyon repository.

Thank you so much!

**Comment by karthik2804** [comment]
The example has been added to the `spin-js-sdk` repo
https://github.com/fermyon/spin-js-sdk/tree/main/examples/typescript/spin_kv
