### ISSUE TITLE
Add a template for Spin + nuxtjs SSG on Spin Up Hub

### ISSUE THREAD

**Issue by macolso** [fermyon/developer#800]
To help developers get started with Spin + SSGs, it would be awesome if we had [Spin Up Hub content](https://developer.fermyon.com/hub) (specifically a template) for nuxtjs.

**Comment by VamshiReddy02** [comment]
Hey @rajatjindal, can I work on this issue? because there is currently no associated pull request for this issue.

**Comment by rajatjindal** [comment]
Yes pls, that would be awesome. Please go ahead 👍

**Comment by tpmccallum** [comment]
Thank you @VamshiReddy02
