### ISSUE TITLE
Add a template for Spin + Docusaurus to Spin Up Hub

### ISSUE THREAD

**Issue by macolso** [fermyon/developer#801]
**Create Docusaurus Template Task**

You can be guided in your contribution by following the [Spin Up Hub Contributor Guide](https://developer.fermyon.com/hub/contributing).

The goal of this task is to create a template (as outlined in the Spin Up Hub documentation above) that will allow a user to deploy a [Docusaurus](https://docusaurus.io/) website via Spin and Fermyon Cloud.

For inspiration on how to get a Static Site Generator to run on Spin see this template called [Spin Hugo](https://developer.fermyon.com/hub/preview/sample_hugo).

One community member [@dipankardas011](https://github.com/dipankardas011) has written [an article on Deploying Docusaraus on Fermyon Cloud](https://medium.com/@dipankardas0115/bridging-distances-deploying-docusaurus-website-on-fermyon-cloud-using-spin-aws-cloudfront-and-fe0609ab79a7) through the use of [kubesimplify](https://github.com/kubesimplify). You may find this inspiring and have some ideas of your own.

If this Static Site Generator (SSG) task interests you, please feel free to check out our other similar tasks:
- [11ty and Spin](https://github.com/fermyon/developer/issues/802)
- [Hugo and Spin](https://github.com/fermyon/developer/issues/803)

**Comment by karthik2804** [comment]
closed by #1098
