### ISSUE TITLE
Key-value section on Python language guide is misleading

### ISSUE THREAD

**Issue by dicej** [fermyon/developer#807]
As of this writing, the [key-value section](https://developer.fermyon.com/spin/python-components#storing-data-in-the-spin-key-value-store) of the Python language guide reads "Spin has a key-value store built in. For information about using it from Rust, see [the key-value store tutorial](https://developer.fermyon.com/spin/kv-store-tutorial)."

Two issues:
- It's the Python guide, so "using it from Rust" isn't relevant
- The linked tutorial doesn't seem to have any Python code examples

I'd suggest we remove the section entirely until the key-value tutorial has Python examples.

**Comment by itowlson** [comment]
Uh oh.  Go and JS mention Rust too.
