### ISSUE TITLE
[Discussion]: Should the compiled VueJS application be removed from source control

### ISSUE THREAD

**Issue by ThorstenHans** [fermyon/developer#825]
Having the compile representation of the Vue application for the Hub in source control, makes keeping multiple PRs independent really hard and requires the reviewer to run `npm run build` in the `spin-up-hub` sub-folder.

IMO building the Vue application for the hub must happen in parallel to running `spin watch` in the root folder locally, and obviously CI/CD must build the app too before publishing a new version to the webserver

**Comment by karthik2804** [comment]
I agree and that is the plan to move it into the CI/CD.
