### ISSUE TITLE
serverless AI: error on plugin install command 

### ISSUE THREAD

**Issue by michelleN** [fermyon/developer#867]
```
$ spin plugins install -u https://github.com/fermyon/cloud-plugin/releases/download/canary/cloud.json - y
error: Found argument 'y' which wasn't expected, or isn't valid in this context
```

**Comment by karthik2804** [comment]
The issue arrives due to the space between the hyphen and the "y"

**Comment by tpmccallum** [comment]
Thanks @karthik2804 
@michelleN is this one ok to close?
Thanks 
Tim

**Comment by tpmccallum** [comment]
Also @michelleN 
If you use the installer from the AI tutorial at https://developer.fermyon.com/spin/serverless-ai-tutorial#spin
The appropriate plugins will be automatically installed (the install script was updated late last week to accommodate)
