### ISSUE TITLE
Reduce animation times to prevent laggy feel

### ISSUE THREAD

**Issue by 404salad** [fermyon/developer#876]
The background animation on hover on the spin/cloud/bartholomew modal is very slow and makes the website appear like its lagging, also all on hover animation on menu items are really slow and feel clunky.

**Comment by 404salad** [comment]
I am willing to work on this, could you assign it to me

**Comment by flynnduism** [comment]
Thanks @404salad for offering to help out here with code contribution! That's awesome. Are you thinking of changing the duration/speed for the dropdown menu, hover effects, etc?

We are _considering_ some Docs changes and are not 100% sure whether the dropdown will remain, so don't worry too much about editing that part right now. If you see other places where you feel like making changes then we would happily review and incorporate suggestions!

**Comment by 404salad** [comment]
Alright! thank you so much for the response. I will keep an eye on the docs! love spin btw
