### ISSUE TITLE
`watch` is missing from the manifest reference documentation

### ISSUE THREAD

**Issue by mikkelhegn** [fermyon/developer#878]
looks like we are missing `watch` in the manifest reference documentation: <https://developer.fermyon.com/spin/manifest-reference#the-componentbuild-table>

[Slack Message](https://fermyon.slack.com/archives/C044P2DFTRS/p1694447352664809)

**Comment by itowlson** [comment]
Duplicate of #875, please re-open if I'm missing a nuance!
