### ISSUE TITLE
Serverless AI Tutorial: npm install may not be applicable

### ISSUE THREAD

**Issue by vdice** [fermyon/developer#880]
I was following the [Serverless AI Tutorial](https://developer.fermyon.com/spin/serverless-ai-tutorial) and chose the Rust path.  However, the docs show `npm install` as a command to run before `spin build --up`.  I wonder if we should add a note to mention this is only needed if the app is TS/JS?

<img width="972" alt="Screenshot 2023-09-12 at 4 14 22 PM" src="https://github.com/fermyon/developer/assets/9322017/2926d852-edeb-4917-90c2-090fb350b431">

**Comment by tpmccallum** [comment]
Thanks @vdice fixed in https://github.com/fermyon/developer/pull/900
