### ISSUE TITLE
Serverless AI Tutorial: Rust path needs serde/serde_json crates

### ISSUE THREAD

**Issue by vdice** [fermyon/developer#881]
I followed the [Serverless AI Tutorial](https://developer.fermyon.com/spin/serverless-ai-tutorial) and chose the Rust path.

## Issue

When running `spin build --up`, I encountered the following errors related to missing the serde/serde_json crates:

<img width="619" alt="Screenshot 2023-09-12 at 4 24 56 PM" src="https://github.com/fermyon/developer/assets/9322017/d5d003d5-062f-4c6c-9c5d-290c2cc740b5">

## Fix

After referencing a Rust app example in the ai-examples repo (https://github.com/fermyon/ai-examples/blob/main/sentiment-analysis-rs/Cargo.toml), I added the following to my Cargo.toml:

```
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.85"
```

Afterwards, I was able to build the app successfully.

(These crates aren't included by default in the [http-rust template](https://github.com/fermyon/spin/blob/main/templates/http-rust/content/Cargo.toml) used for the tutorial, hence needing to add them manually)

**Comment by tpmccallum** [comment]
Thanks @vdice fixed in https://github.com/fermyon/developer/pull/900
