### ISSUE TITLE
Mystery black border flash when dropping down Docs menu

### ISSUE THREAD

**Issue by itowlson** [fermyon/developer#884]
I went to the docs homepage and moved the mouse over the Docs drop-down.  When I did this, the background gradually blurred, and a strange blurry black border started to appear around the edges of the (visible area of the) page.  After a moment the blur reached its maximum blurriness at which point the black border suddenly vanished.

MS Edge on Windows 10.

![image](https://github.com/fermyon/developer/assets/865538/af32d8aa-1cb7-40eb-a118-b83188be7dcb)

**Comment by itowlson** [comment]
cc @karthik2804 @flynnduism since this has the stench of CSS about it

**Comment by itowlson** [comment]
@karthik2804 told me this was some sort of hardware acceleration bug in the blur effect and there's nothing we can do about it.  Should we:

1. Close this issue because can't fix won't fix
2. Leave this open so it's visible next time I go "what's this ugly black border"
3. Replace the blur effect with something that doesn't have a hardware acceleration bug
4. Something else

**Comment by karthik2804** [comment]
I'm gonna check on this again to make sure I did not gloss over it and try alternative effects in case the blur causes issues.
