### ISSUE TITLE
Unable to Follow Contribution Guide: Error with directories.

### ISSUE THREAD

**Issue by stephanhorvath** [fermyon/developer#885]
I am trying to follow the contribution guide to add my own small project to the Hub. I am running into a problem when I get to the `Testing Locally` section.

Specs:
- Macbook Pro 2019
- 2,3 GHz 8-Core Intel Core i9
- 16 GB 2400 MHz DDR4
- macOS 13.5

When I run `npm run spin`, I get the following output on my Terminal:

```
❯ npm run spin

> developer-fermyon-com@0.1.0 spin
> nodemon --watch content --watch static --watch templates --watch spin-up-hub --ext html,md,rhai,hbs,css,js --verbose --legacy-watch --signal SIGINT --exec 'npm run build-index && npm run build-hub-index && spin up --file spin.toml --quiet --env PREVIEW_MODE=$PREVIEW_MODE'

[nodemon] 2.0.20
[nodemon] to restart at any time, enter `rs`
[nodemon] or send SIGUSR2 to 56478 to restart
[nodemon] watching path(s): content/**/* static/**/* templates/**/* spin-up-hub/**/*
[nodemon] watching extensions: html,md,rhai,hbs,css,js
[nodemon] starting `npm run build-index && npm run build-hub-index && spin up --file spin.toml --quiet --env PREVIEW_MODE=$PREVIEW_MODE`
[nodemon] spawning
[nodemon] child pid: 56493
[nodemon] watching 338 files

> developer-fermyon-com@0.1.0 build-index
> node md_parser.mjs --dir=./content/ --out=./static/data.json --ignore=./content/api/**/*

[nodemon] files triggering change check: static/data.json
[nodemon] matched rule: /Users/sh/code/projects/fermyon/developer/static/**/*
[nodemon] changes after filters (before/after): 1/0

> developer-fermyon-com@0.1.0 build-hub-index
> node hub_index_generator.mjs --dir=./content/api/hub/ --out=./static/hub-index-data.json --ignore=./content/api/hub/get_list.md,

[nodemon] files triggering change check: static/hub-index-data.json
[nodemon] matched rule: /Users/sh/code/projects/fermyon/developer/static/**/*
[nodemon] changes after filters (before/after): 1/0
Error: Failed to collect file mounts for spin-up-hub/dist/

Caused by:
      Cannot place /Users/sh/code/projects/fermyon/developer/spin-up-hub/dist/: source must be a directory
[nodemon] app crashed - waiting for file changes before starting...

```

The error lies in `spin-up-hub/dist` not existing. This is my first time contributing to anything, so if there is more information I need to provide, I will gladly do so.

Thank you for your patience.

**Comment by itowlson** [comment]
@stephanhorvath Thanks for letting us know, and I'm sorry your first time contributing (welcome!) has been frustrating.

I've run into this error too.  I think one needs to build the Spin Up Hub separately first (as a one-off) - cd spin-up-hub then npm install and npm run build (then cd back to the repo root).  I thought we had written this down but now I can't find it!

@karthik2804 can you confirm?

**Comment by itowlson** [comment]
@karthik2804 bump to confirm if we need new instructions and if so what they are

**Comment by karthik2804** [comment]
@itowlson Sorry for the delay and yes.  

One has to `npm install`  in `spin-up-hub` and then run `spin build` from the root of the project.

**Comment by stephanhorvath** [comment]
Thank you both! Worked like a charm.
