### ISSUE TITLE
Discern which spin templates will **not** work with cloud and then communicate to audience

### ISSUE THREAD

**Issue by tpmccallum** [fermyon/developer#90]
At present there is a chance that a user will create a spin app (using one of the templates) which will **not** necessarily work when deployed to the cloud. Perhaps the best example is a `redis-rust` template application. When we attempted to deploy this template to the cloud an issue was raised < https://github.com/fermyon/developer/issues/89 >

Perhaps we can tick off templates that are known to **not** work (via the following list) and then add this to the documentation in the long term.

Templates which are currently **not** compatible with Fermyon Cloud:

- [ ] http-c        HTTP request handler using C and the Zig toolchain 
- [ ] http-csharp   HTTP request handler using C# (EXPERIMENTAL)       
- [ ] http-go       HTTP request handler using (Tiny)Go                
- [ ] http-grain    HTTP request handler using Grain                   
- [ ] http-rust     HTTP request handler using Rust                    
- [ ] http-swift    HTTP request handler using SwiftWasm               
- [ ] http-zig      HTTP request handler using Zig                     
- [x] redis-go      Redis message handler using (Tiny)Go               
- [x] redis-rust    Redis message handler using Rust

**Comment by macolso** [comment]
I've created an issue to track adding `redis-trigger` support on cloud: https://github.com/fermyon/cloud/issues/1296
