### ISSUE TITLE
If we are not already using npm ci  on our CI,we should switch.

### ISSUE THREAD

**Issue by tpmccallum** [fermyon/developer#922]
Did a preview of docs locally

```bash
cd spin-up-hub
npm install
cd ../
npm install
spin build
spin up -e "PREVIEW_MODE=1"
```

Then git `add`, `commit` and `push` and the `*lock.json` made it into the PR.

See https://github.com/fermyon/developer/pull/920/files

**Comment by tpmccallum** [comment]
Hi @vdice not sure how to implement `npm ci` instead of `npm install`. Is this something we can collaborate on, or you can look at and update from your end?

**Comment by itowlson** [comment]
We are already using `npm ci` in our CI.  But the issue description is about _locally_ using `npm install` instead of `npm ci`, which we can describe in contributing docs but can't control.

**Comment by tpmccallum** [comment]
Right you are, updated the docs so that users can just `npm ci` and this was all resolved (also we definitely use `npm ci` on the GH build side).
