### ISSUE TITLE
Document Spin's Postgres support in JavaScript

### ISSUE THREAD

**Issue by tpmccallum** [fermyon/developer#932]
Currently only Rust examples; so duplicate the fashion in which Rust Postgress support is done i.e. similar page, heading, codeblock example.

**Comment by janpio** [comment]
Affected page: https://developer.fermyon.com/spin/v2/rdbms-storage
And example showing actual usage: https://github.com/fermyon/spin-js-sdk/blob/main/examples/typescript/outbound_mysql/src/index.ts

**Comment by tpmccallum** [comment]
Please see https://github.com/fermyon/developer/pull/1029
And see the TS/JS tab at https://developer.fermyon.com/spin/v2/rdbms-storage

**Comment by janpio** [comment]
Wheee!
