### ISSUE TITLE
Language filtering on Spin Up Hub (Using "Sample" and "JS/TS" returns blank)

### ISSUE THREAD

**Issue by tpmccallum** [fermyon/developer#939]
Not sure how the Hub filters in the UI, but clicking on both "Sample" and "JS/TS" returns a blank page:

<img width="890" alt="Screenshot 2023-10-20 at 11 50 04" src="https://github.com/fermyon/developer/assets/9831342/4443b2d8-d903-48be-9fb9-0571e3deefad">

Other combinations seem to work.

**Comment by itowlson** [comment]
The `JS/TS` filter seems to omit a _lot_ of our JavaScript stuff.  For me it showed only 5 items; going through the Hub looking at the tags I counted 12.

**Comment by itowlson** [comment]
Ah, some items use a Language of "TypeScript" (or JavaScript?) and some use "JS/TS"; the filter isn't considering the "TypeScript" ones.
